<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Calendar – {{ $business->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false}"><div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'calendar'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><div class="flex items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">{{ $business->name }}</p><h1 class="mt-1 text-xl font-extrabold">Calendar</h1></div><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">External calendars · Connection pending</span></div></header>
<main class="mx-auto max-w-[1600px] px-4 py-6 lg:px-6">
@if(session('status'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div class="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-bold">The block could not be saved.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div class="flex items-center gap-3"><a href="{{ route('owner.calendar',['month'=>$previousMonth,'property'=>$selectedProperty]) }}" class="rounded-lg border bg-white px-3 py-2 font-bold">←</a><h2 class="min-w-48 text-center text-xl font-extrabold">{{ $monthStart->format('F Y') }}</h2><a href="{{ route('owner.calendar',['month'=>$nextMonth,'property'=>$selectedProperty]) }}" class="rounded-lg border bg-white px-3 py-2 font-bold">→</a></div><form method="GET" class="flex gap-2"><input type="hidden" name="month" value="{{ $monthStart->format('Y-m') }}"><select name="property" class="rounded-lg border-slate-200 bg-white text-sm"><option value="">All properties</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected($selectedProperty===$property->id)>{{ $property->name }}</option>@endforeach</select><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Apply</button></form></div>
<section class="mt-5 rounded-xl border border-slate-200 bg-white p-4"><div class="flex flex-col gap-1"><h3 class="text-sm font-extrabold">Block dates</h3><p class="text-xs text-slate-500">Reserve dates for maintenance, owner stays, or operational work.</p></div><form method="POST" action="{{ route('owner.calendar.blocks.store') }}" class="mt-4 grid gap-3 md:grid-cols-[minmax(12rem,1.3fr)_1fr_1fr_minmax(12rem,1.5fr)_auto] md:items-end">@csrf<input type="hidden" name="month" value="{{ $monthStart->format('Y-m') }}"><label class="text-xs font-bold text-slate-600">Property<select name="property_id" required class="mt-1 block w-full rounded-lg border-slate-200 text-sm"><option value="">Select property</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected(old('property_id',$selectedProperty)===$property->id)>{{ $property->name }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-600">From<input type="date" name="starts_on" value="{{ old('starts_on') }}" required class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Until<input type="date" name="ends_on" value="{{ old('ends_on') }}" required class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Reason<input type="text" name="reason" value="{{ old('reason') }}" required maxlength="1000" placeholder="e.g. Planned maintenance" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Block dates</button></form></section>
<section class="mt-5 overflow-x-auto rounded-xl border border-slate-200 bg-white"><div class="min-w-[760px]"><div class="grid grid-cols-7 border-b bg-slate-50 text-center text-[11px] font-bold uppercase tracking-wider text-slate-500">@foreach(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'] as $weekday)<div class="p-3">{{ $weekday }}</div>@endforeach</div><div class="grid grid-cols-7">@foreach($days as $day)<div class="min-h-28 border-b border-r p-2 {{ $day['in_month']?'bg-white':'bg-slate-50 text-slate-300' }}"><p class="text-xs font-bold">{{ $day['date']->day }}</p><div class="mt-2 space-y-1">@foreach($day['events']->take(3) as $event)@if($event['type']==='booking')<a href="{{ route('owner.bookings.show',$event['booking_id']) }}" title="{{ $event['property'] }}" class="block truncate rounded bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-700">{{ $event['label'] }}</a>@else<span title="{{ $event['property'] }}" class="block truncate rounded bg-red-50 px-2 py-1 text-[10px] font-bold text-red-700">{{ $event['label'] }}</span>@endif @endforeach</div></div>@endforeach</div></div></section>
@if($blocks->isNotEmpty())<section class="mt-5 rounded-xl border border-slate-200 bg-white p-4"><h3 class="text-sm font-extrabold">Active blocks in this view</h3><div class="mt-3 divide-y divide-slate-100">@foreach($blocks->sortBy('starts_on') as $block)<div class="flex flex-col justify-between gap-3 py-3 sm:flex-row sm:items-center"><div><p class="text-sm font-bold">{{ $block->property->name }}</p><p class="text-xs text-slate-500">{{ $block->starts_on->format('d M Y') }} – {{ $block->ends_on->format('d M Y') }} · {{ $block->reason ?: 'Blocked' }}</p></div>@if($block->source_type==='owner')<form method="POST" action="{{ route('owner.calendar.blocks.destroy',$block) }}">@csrf @method('DELETE')<input type="hidden" name="month" value="{{ $monthStart->format('Y-m') }}"><input type="hidden" name="property" value="{{ $selectedProperty }}"><button class="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Release</button></form>@endif</div>@endforeach</div></section>@endif
<div class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-xl border bg-white p-4"><p class="text-2xl font-extrabold">{{ $bookings->count() }}</p><p class="text-xs text-slate-500">Blocking bookings this view</p></div><div class="rounded-xl border bg-white p-4"><p class="text-2xl font-extrabold">{{ $blocks->count() }}</p><p class="text-xs text-slate-500">Manual or operational blocks</p></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="text-sm font-bold text-amber-800">Connection pending</p><p class="mt-1 text-xs text-amber-700">Airbnb, Booking.com and iCal synchronization will be connected later.</p></div></div>
</main></div></div></body></html>
