<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review {{ $property->name }} - Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-gray-100 font-sans antialiased"><div class="min-h-screen flex flex-col"><header class="border-b border-gray-200 bg-white"><div class="mx-auto flex max-w-5xl items-center justify-between px-6 py-3"><div class="flex items-center gap-2"><img src="/logo1.png" alt="VS Logo" class="h-7"><span class="text-sm font-semibold">Verified Shortlet</span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-500">Step 10 of 10</span><a href="{{ route('owner.properties.index') }}" class="rounded-lg border px-3 py-1.5 text-xs">Save & exit</a></div></div><div class="h-0.5 bg-[#FF5A00]"></div></header>
<main class="flex-1 px-4 py-7"><div class="mx-auto w-full max-w-5xl"><div class="mb-5"><p class="text-xs font-bold uppercase tracking-wider text-[#FF5A00]">Last look</p><h1 class="mt-1 text-2xl font-bold">Review your complete listing</h1><p class="mt-1 text-sm text-gray-500">Check every detail, image and document saved by the property owner before submitting.</p></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="grid gap-4 lg:grid-cols-2">
@php $cards=[
[2,'Location',[data_get($property->address,'line_1'),collect([data_get($property->address,'city'),data_get($property->address,'state'),data_get($property->address,'country_code')])->filter()->join(', ')]],
[3,'Property details',[str($property->property_type)->replace('_',' ')->title().' · Entire place',$property->capacity.' guests · '.$property->bedrooms.' bedrooms · '.$property->bathrooms.' bathrooms']],
[8,'Name, description & price',[$property->name,$property->description ?: 'No description added',$property->pricing_currency.' '.number_format((float)$property->default_nightly_price).' / night']],
]; @endphp
@foreach($cards as [$step,$title,$lines])<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between gap-3"><h2 class="font-bold">{{ $title }}</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>$step]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div>@foreach($lines as $line)<p class="mt-1 text-sm text-gray-600">{{ $line ?: 'Not provided' }}</p>@endforeach</section>@endforeach
<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-bold">Amenities</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>4]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="flex flex-wrap gap-2">@forelse($property->amenities as $amenity)<span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold">{{ $amenity->name }}</span>@empty<p class="text-sm text-gray-500">None selected</p>@endforelse</div></section>
@php $photoCount=$property->media->filter(fn($item)=>$item->media_type->value==='image')->count(); $videoCount=$property->media->filter(fn($item)=>$item->media_type->value==='video')->count(); @endphp
<section class="rounded-xl border border-gray-200 bg-white p-5 lg:col-span-2"><div class="mb-4 flex justify-between"><div><h2 class="font-bold">Photos & video</h2><p class="text-xs text-gray-500">{{ $photoCount }} {{ Str::plural('photo', $photoCount) }} · {{ $videoCount }} {{ Str::plural('video', $videoCount) }}</p></div><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>5]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">@forelse($property->media as $media)@php $mediaType=$media->media_type->value; $mediaUrl='/storage/'.ltrim($media->storage_path,'/'); @endphp<div class="group overflow-hidden rounded-xl border border-gray-200 bg-gray-50 shadow-sm"><div class="relative aspect-video overflow-hidden bg-gray-900">@if($mediaType==='video')<video controls preload="metadata" playsinline src="{{ $mediaUrl }}" class="h-full w-full object-contain">Your browser cannot play this video.</video><span class="pointer-events-none absolute left-2 top-2 rounded-full bg-black/70 px-2 py-1 text-[10px] font-bold text-white">VIDEO</span>@else<img src="{{ $mediaUrl }}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105" alt="{{ $media->alt_text ?: $media->title }}">@if($media->is_primary)<span class="absolute left-2 top-2 rounded-full bg-[#FF5A00] px-2 py-1 text-[10px] font-bold text-white">COVER PHOTO</span>@endif @endif</div><div class="p-3"><p class="truncate text-sm font-semibold text-gray-900" title="{{ $media->title }}">{{ $media->title ?: ucfirst($mediaType) }}</p><p class="mt-0.5 text-xs capitalize text-gray-500">{{ $mediaType }}</p></div></div>@empty<p class="text-sm text-gray-500">No media uploaded</p>@endforelse</div></section>
<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-bold">Items inside the flat</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>6]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><ul class="space-y-1 text-sm text-gray-600">@forelse($property->assets->where('status','active') as $asset)<li>• {{ str($asset->name)->replace('-',' ')->ucfirst() }}</li>@empty<li>None added</li>@endforelse</ul></section>
<section class="rounded-xl border border-gray-200 bg-white p-5 lg:col-span-2"><div class="mb-4 flex justify-between"><div><h2 class="font-bold">Documents</h2><p class="text-xs text-gray-500">{{ $property->documents->count() }} {{ Str::plural('file', $property->documents->count()) }} attached</p></div><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>7]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($property->documents as $document)@php $version=$document->versions->sortByDesc('version_number')->first(); $mime=$version?->mime_type ?: 'application/octet-stream'; $isImage=str_starts_with($mime,'image/'); $extension=strtoupper(pathinfo($version?->original_name ?: $document->title,PATHINFO_EXTENSION) ?: 'FILE'); $previewUrl=route('owner.properties.wizard.documents.preview',['property'=>$property,'document'=>$document]); @endphp<a target="_blank" rel="noopener" href="{{ $previewUrl }}" class="group overflow-hidden rounded-xl border border-gray-200 bg-gray-50 transition hover:border-orange-300 hover:shadow-sm">@if($isImage)<div class="aspect-[16/9] overflow-hidden bg-gray-100"><img src="{{ $previewUrl }}" alt="Preview of {{ $document->title }}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105"></div>@else<div class="flex aspect-[16/9] items-center justify-center bg-gradient-to-br from-gray-100 to-gray-200"><div class="rounded-lg bg-white px-4 py-3 text-sm font-black text-gray-600 shadow-sm">{{ $extension }}</div></div>@endif<div class="flex items-center justify-between gap-3 p-3"><div class="min-w-0"><p class="truncate text-sm font-semibold text-gray-900" title="{{ $document->title }}">{{ $document->title }}</p><p class="mt-0.5 text-xs text-gray-500">{{ $version?->size_bytes ? number_format($version->size_bytes / 1024, 0).' KB' : $extension }}</p></div><span class="shrink-0 rounded-lg bg-orange-50 px-2.5 py-1.5 text-xs font-bold text-orange-700">Preview</span></div></a>@empty<p class="text-sm text-gray-500">No documents uploaded</p>@endforelse</div></section>
<section class="rounded-xl border border-gray-200 bg-white p-5 lg:col-span-2"><div class="mb-3 flex justify-between"><h2 class="font-bold">Booking channels</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>9]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Verified Shortlet · Active</span>@foreach($property->channelConnections->where('status','active') as $channel)<span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{{ $channel->provider==='bookingcom'?'Booking.com':str($channel->provider)->title() }} · Connection pending</span>@endforeach</div></section>
</div>
<div class="my-6 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-gray-700">Submitting sends this complete listing for platform-admin verification. It remains pending until approved.</div>
<div x-data="{confirmOpen:false,submitting:false}" @keydown.escape.window="if(!submitting) confirmOpen=false">
    <div class="flex items-center justify-between">
        <a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>9]) }}" class="text-sm text-gray-500 underline">Back</a>
        <button type="button" @click="confirmOpen=true;$nextTick(()=>$refs.confirmButton.focus())" class="rounded-lg bg-[#FF5A00] px-8 py-2.5 text-sm font-bold text-white shadow-md transition hover:bg-[#E55000] focus:outline-none focus:ring-2 focus:ring-orange-300 focus:ring-offset-2">Submit for review</button>
    </div>

    <div x-show="confirmOpen" x-cloak x-transition.opacity class="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="submit-confirmation-title">
        <button type="button" aria-label="Close confirmation" class="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" @click="if(!submitting) confirmOpen=false"></button>
        <div x-show="confirmOpen" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-y-4 scale-95 opacity-0" x-transition:enter-end="translate-y-0 scale-100 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-y-0 scale-100 opacity-100" x-transition:leave-end="translate-y-4 scale-95 opacity-0" class="relative w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl">
            <div class="bg-gradient-to-br from-orange-50 to-white px-6 pb-5 pt-6 text-center">
                <div class="mx-auto flex size-14 items-center justify-center rounded-full bg-orange-100 text-[#FF5A00] ring-8 ring-orange-50">
                    <svg class="size-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                </div>
                <h2 id="submit-confirmation-title" class="mt-5 text-xl font-extrabold text-gray-900">Ready to submit?</h2>
                <p class="mt-2 text-sm leading-6 text-gray-600"><strong>{{ $property->name }}</strong> will be sent to the Verified Shortlet team for review.</p>
            </div>
            <div class="border-y border-gray-100 px-6 py-4">
                <div class="flex gap-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-900"><svg class="mt-0.5 size-5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><p>The listing will remain pending until an administrator approves it. You can continue managing the property from your dashboard.</p></div>
            </div>
            <form method="POST" action="{{ route('owner.properties.wizard.submit',$property) }}" @submit="submitting=true" class="flex flex-col-reverse gap-3 p-6 sm:flex-row sm:justify-end">@csrf
                <button type="button" @click="confirmOpen=false" :disabled="submitting" class="rounded-lg border border-gray-300 px-5 py-2.5 text-sm font-bold text-gray-700 transition hover:bg-gray-50 disabled:opacity-50">Go back and edit</button>
                <button x-ref="confirmButton" type="submit" :disabled="submitting" class="inline-flex items-center justify-center rounded-lg bg-[#FF5A00] px-5 py-2.5 text-sm font-bold text-white shadow-md transition hover:bg-[#E55000] disabled:cursor-wait disabled:opacity-70">
                    <svg x-show="submitting" class="mr-2 size-4 animate-spin" viewBox="0 0 24 24" fill="none"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"/></svg>
                    <span x-text="submitting ? 'Submitting…' : 'Yes, submit listing'">Yes, submit listing</span>
                </button>
            </form>
        </div>
    </div>
</div>
</div></main></div></body></html>
