<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review {{ $property->name }} - Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-gray-100 font-sans antialiased"><div class="min-h-screen flex flex-col"><header class="border-b border-gray-200 bg-white"><div class="mx-auto flex max-w-5xl items-center justify-between px-6 py-3"><div class="flex items-center gap-2"><img src="/logo1.png" alt="VS Logo" class="h-7"><span class="text-sm font-semibold">Verified Shortlet</span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-500">Step 10 of 10</span><a href="{{ route('owner.properties.index') }}" class="rounded-lg border px-3 py-1.5 text-xs">Save & exit</a></div></div><div class="h-0.5 bg-[#FF5A00]"></div></header>
<main class="flex-1 px-4 py-7"><div class="mx-auto w-full max-w-5xl"><div class="mb-5"><p class="text-xs font-bold uppercase tracking-wider text-[#FF5A00]">Last look</p><h1 class="mt-1 text-2xl font-bold">Review your complete listing</h1><p class="mt-1 text-sm text-gray-500">Check every detail, image and document saved by the property owner before submitting.</p></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="grid gap-4 lg:grid-cols-2">
@php $cards=[
[2,'Location',[data_get($property->address,'line_1'),collect([data_get($property->address,'city'),data_get($property->address,'state'),data_get($property->address,'country_code')])->filter()->join(', ')]],
[3,'Property details',[str($property->property_type)->replace('_',' ')->title().' · Entire place',$property->capacity.' guests · '.$property->bedrooms.' bedrooms · '.$property->bathrooms.' bathrooms']],
[8,'Name, description & price',[$property->name,$property->description ?: 'No description added',$property->pricing_currency.' '.number_format((float)$property->default_nightly_price).' / night']],
]; @endphp
@foreach($cards as [$step,$title,$lines])<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between gap-3"><h2 class="font-bold">{{ $title }}</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>$step]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div>@foreach($lines as $line)<p class="mt-1 text-sm text-gray-600">{{ $line ?: 'Not provided' }}</p>@endforeach</section>@endforeach
<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-bold">Amenities</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>4]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="flex flex-wrap gap-2">@forelse($property->amenities as $amenity)<span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold">{{ $amenity->name }}</span>@empty<p class="text-sm text-gray-500">None selected</p>@endforelse</div></section>
<section class="rounded-xl border border-gray-200 bg-white p-5 lg:col-span-2"><div class="mb-3 flex justify-between"><div><h2 class="font-bold">Photos & video</h2><p class="text-xs text-gray-500">{{ $property->media->where('media_type','image')->count() }} photos · {{ $property->media->where('media_type','video')->count() }} video</p></div><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>5]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-4">@forelse($property->media as $media)<div class="overflow-hidden rounded-lg border">@if($media->media_type==='video')<video controls src="{{ Storage::disk($media->storage_disk)->url($media->storage_path) }}" class="h-32 w-full object-cover"></video>@else<img src="{{ Storage::disk($media->storage_disk)->url($media->storage_path) }}" class="h-32 w-full object-cover" alt="{{ $media->title }}">@endif<div class="truncate px-2 py-1.5 text-xs font-semibold">{{ $media->title }}</div></div>@empty<p class="text-sm text-gray-500">No media uploaded</p>@endforelse</div></section>
<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-bold">Items inside the flat</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>6]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><ul class="space-y-1 text-sm text-gray-600">@forelse($property->assets->where('status','active') as $asset)<li>• {{ str($asset->name)->replace('-',' ')->ucfirst() }}</li>@empty<li>None added</li>@endforelse</ul></section>
<section class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-bold">Documents</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>7]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="space-y-2">@forelse($property->documents as $document)<a target="_blank" rel="noopener" href="{{ route('owner.properties.wizard.documents.preview',['property'=>$property,'document'=>$document]) }}" class="flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-sm font-semibold hover:bg-orange-50"><span>{{ $document->title }}</span><span class="text-xs text-orange-600">Preview</span></a>@empty<p class="text-sm text-gray-500">No documents uploaded</p>@endforelse</div></section>
<section class="rounded-xl border border-gray-200 bg-white p-5 lg:col-span-2"><div class="mb-3 flex justify-between"><h2 class="font-bold">Booking channels</h2><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>9]) }}" class="text-sm font-semibold text-[#FF5A00]">Edit</a></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Verified Shortlet · Active</span>@foreach($property->channelConnections->where('status','active') as $channel)<span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{{ $channel->provider==='bookingcom'?'Booking.com':str($channel->provider)->title() }} · Connection pending</span>@endforeach</div></section>
</div>
<div class="my-6 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-gray-700">Submitting sends this complete listing for platform-admin verification. It remains pending until approved.</div><div class="flex items-center justify-between"><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>9]) }}" class="text-sm text-gray-500 underline">Back</a><form method="POST" action="{{ route('owner.properties.wizard.submit',$property) }}">@csrf<button class="rounded-lg bg-[#FF5A00] px-8 py-2.5 text-sm font-bold text-white">Submit for review</button></form></div>
</div></main></div></body></html>
