<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Property - Step 3 - Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-gray-100 font-sans antialiased" x-data="{type:@js(old('property_type',in_array($property->property_type,['flat','duplex','apartment'],true)?$property->property_type:'apartment')),guests:{{ old('capacity',$property->capacity) }},bedrooms:{{ old('bedrooms',$property->bedrooms) }},bathrooms:{{ old('bathrooms',$property->bathrooms) }}}">
<div class="min-h-screen flex flex-col"><header class="bg-white border-b border-gray-200"><div class="max-w-3xl mx-auto px-6 py-3 flex items-center justify-between"><div class="flex items-center gap-2"><img src="/logo1.png" alt="VS Logo" class="h-7"><span class="text-sm font-semibold">Verified Shortlet</span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-500">Step 3 of 10</span><a href="{{ route('owner.properties.index') }}" class="px-3 py-1.5 text-xs border rounded-lg">Save & exit</a></div></div><div class="h-0.5 bg-gray-200"><div class="h-0.5 bg-[#FF5A00]" style="width:30%"></div></div></header>
<main class="flex-1 py-7 px-4"><form method="POST" action="{{ route('owner.properties.wizard.store',['property'=>$property,'step'=>3]) }}" class="max-w-3xl mx-auto">@csrf
<input type="hidden" name="property_type" x-model="type"><input type="hidden" name="booking_mode" value="entire"><input type="hidden" name="capacity" x-model="guests"><input type="hidden" name="bedrooms" x-model="bedrooms"><input type="hidden" name="bathrooms" x-model="bathrooms">
@if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="mb-5"><p class="text-[#FF5A00] text-xs font-bold uppercase tracking-widest mb-1.5">The basics</p><h1 class="text-2xl font-bold">Tell us about the place</h1><p class="mt-1.5 text-sm text-gray-500">A few quick facts guests use to decide if it fits them.</p></div>
<p class="mb-4 text-sm font-semibold text-gray-800">What kind of place is it?</p><div class="grid grid-cols-1 gap-3 sm:grid-cols-3">@foreach(['flat'=>'Flat','duplex'=>'Duplex','apartment'=>'Apartment'] as $value=>$label)<button type="button" @click="type=@js($value)" class="rounded-xl border-2 bg-white p-5 text-left transition" :class="type===@js($value)?'border-[#FF5A00] bg-orange-50':'border-gray-200 hover:border-gray-300'"><svg class="mb-3 size-8" viewBox="0 0 24 24" fill="currentColor"><path d="M4 21V9l8-6 8 6v12h-5v-7H9v7z"/></svg><span class="font-bold">{{ $label }}</span><span x-show="type===@js($value)" class="mt-3 block text-[10px] font-bold text-[#FF5A00]">SELECTED</span></button>@endforeach</div>
{{-- Private rooms, shared rooms and multiple bookable rooms are intentionally deferred for the serviced-apartment MVP. --}}
<section class="mt-7 rounded-xl border border-gray-200 bg-white"><div class="p-6"><p class="font-bold">Guests book the entire serviced apartment</p><p class="mt-1 text-sm text-gray-500">Multiple bookable rooms will be available in a later version.</p></div><div class="border-t border-gray-100 px-6"><p class="pt-5 pb-2 text-sm font-bold">Capacity</p>
@foreach([['guests','Guests','Maximum number of guests allowed',1],['bedrooms','Bedrooms','',0],['bathrooms','Bathrooms',"Add .5 for a visitor's toilet with no bath",0]] as [$model,$label,$help,$minimum])<div class="flex items-center justify-between border-b border-gray-100 py-4 last:border-0"><div><p class="text-sm font-semibold">{{ $label }}</p>@if($help)<p class="mt-0.5 text-xs text-gray-500">{{ $help }}</p>@endif</div><div class="flex items-center gap-3"><button type="button" @click="{{ $model }}=Math.max({{ $minimum }},{{ $model }}-1)" class="size-8 rounded-full border">−</button><span class="w-6 text-center text-sm font-semibold" x-text="{{ $model }}"></span><button type="button" @click="{{ $model }}++" class="size-8 rounded-full border">+</button></div></div>@endforeach
</div><div class="flex items-center justify-between border-t border-gray-100 px-6 py-5"><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>2]) }}" class="text-sm text-gray-500 underline">Back</a><button class="rounded-lg bg-[#FF5A00] px-8 py-2.5 text-sm font-bold text-white">Next Step</button></div></section>
</form></main></div></body></html>
