<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Property - Step 9 - Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-gray-100 font-sans antialiased"><div class="min-h-screen flex flex-col"><header class="border-b border-gray-200 bg-white"><div class="mx-auto flex max-w-4xl items-center justify-between px-6 py-3"><div class="flex items-center gap-2"><img src="/logo1.png" alt="VS Logo" class="h-7"><span class="text-sm font-semibold">Verified Shortlet</span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-500">Step 9 of 10</span><a href="{{ route('owner.properties.index') }}" class="rounded-lg border px-3 py-1.5 text-xs">Save & exit</a></div></div><div class="h-0.5 bg-gray-200"><div class="h-0.5 bg-[#FF5A00]" style="width:90%"></div></div></header>
<main class="flex-1 px-4 py-7"><form method="POST" action="{{ route('owner.properties.wizard.store',['property'=>$property,'step'=>9]) }}" class="mx-auto w-full max-w-4xl">@csrf
<div class="mb-6"><p class="text-xs font-bold uppercase tracking-wider text-[#FF5A00]">Distribution channels</p><h1 class="mt-1.5 text-2xl font-bold">Where do you want to take bookings?</h1><p class="mt-1.5 text-sm text-gray-500">Select your channels. For Airbnb or Booking.com, paste that platform's calendar export URL to prevent double bookings.</p></div>
@php $selected=$property->channelConnections->where('status','active')->pluck('provider')->all(); $connections=$property->externalCalendarConnections->keyBy('provider'); $channels=['airbnb'=>['Airbnb','Paste the Airbnb calendar export (.ics) URL.'],'bookingcom'=>['Booking.com','Paste the Booking.com calendar export (.ics) URL.'],'whatsapp'=>['WhatsApp','Manual bookings from your business number.']]; @endphp
<section class="space-y-3"><div class="flex items-center gap-4 rounded-xl border border-orange-200 bg-white p-5"><span class="flex size-11 items-center justify-center rounded-xl bg-[#FF5A00] font-bold text-white">VS</span><div class="flex-1"><h2 class="font-bold">Verified Shortlet — Direct</h2><p class="mt-1 text-xs text-gray-500">Always enabled for marketplace bookings.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold text-emerald-700">ACTIVE</span></div>
@foreach($channels as $provider=>[$name,$description])@php $externalConnection=$connections->get($provider); @endphp<div class="rounded-xl border border-gray-200 bg-white p-5 hover:border-orange-300"><label class="flex cursor-pointer items-center gap-4"><input type="checkbox" name="channels[]" value="{{ $provider }}" @checked(in_array($provider,$selected,true)) class="size-5 rounded border-gray-300 text-[#FF5A00] focus:ring-[#FF5A00]"><div class="flex-1"><h2 class="font-bold">{{ $name }}</h2><p class="mt-1 text-xs text-gray-500">{{ $description }}</p></div><span class="rounded-full {{ $externalConnection ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }} px-3 py-1 text-[10px] font-bold">{{ $externalConnection ? strtoupper($externalConnection->sync_status) : 'NOT CONNECTED' }}</span></label>@if(in_array($provider,['airbnb','bookingcom'],true))<input type="url" name="calendar_urls[{{ $provider }}]" value="{{ old('calendar_urls.'.$provider, $externalConnection?->inboundFeedUrl()) }}" placeholder="https://...calendar....ics" class="mt-4 block w-full rounded-lg border-gray-200 text-sm" aria-label="{{ $name }} calendar export URL">@endif</div>@endforeach
<div class="flex items-center gap-4 rounded-xl border border-gray-200 bg-gray-50 p-5 opacity-70"><input type="checkbox" checked disabled class="size-5 rounded"><div class="flex-1"><h2 class="font-bold">Walk-in / Phone call</h2><p class="mt-1 text-xs text-gray-500">Always available for manual bookings.</p></div><span class="text-xs font-semibold text-gray-500">Always on</span></div></section>
<div class="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-gray-700">No API key is required. After saving, use Calendar sync on the property details page to copy the Verified Shortlet export URL back into Airbnb or Booking.com.</div>
<div class="mt-6 flex items-center justify-between"><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>8]) }}" class="text-sm text-gray-500 underline">Back</a><div class="flex gap-3"><button type="submit" formaction="{{ route('owner.properties.wizard.skip',['property'=>$property,'step'=>9]) }}" class="text-sm text-gray-500 underline">Skip for now</button><button class="rounded-lg bg-[#FF5A00] px-8 py-2.5 text-sm font-bold text-white">Next Step</button></div></div>
</form></main></div></body></html>
