<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Property - Step 9 - Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-gray-100 font-sans antialiased"><div class="min-h-screen flex flex-col"><header class="border-b border-gray-200 bg-white"><div class="mx-auto flex max-w-4xl items-center justify-between px-6 py-3"><div class="flex items-center gap-2"><img src="/logo1.png" alt="VS Logo" class="h-7"><span class="text-sm font-semibold">Verified Shortlet</span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-500">Step 9 of 10 · Optional</span><a href="{{ route('owner.properties.index') }}" class="rounded-lg border px-3 py-1.5 text-xs">Save & exit</a></div></div><div class="h-0.5 bg-gray-200"><div class="h-0.5 bg-[#FF5A00]" style="width:90%"></div></div></header>
<main class="flex-1 px-4 py-7"><form method="POST" action="{{ route('owner.properties.wizard.store',['property'=>$property,'step'=>9]) }}" class="mx-auto w-full max-w-4xl">@csrf
<div class="mb-6"><div class="flex items-center gap-2"><p class="text-xs font-bold uppercase tracking-wider text-[#FF5A00]">Distribution channels</p><span class="rounded-full bg-gray-200 px-2 py-0.5 text-[10px] font-bold text-gray-600">OPTIONAL</span></div><h1 class="mt-1.5 text-2xl font-bold">Where do you want to take bookings?</h1><p class="mt-1.5 text-sm text-gray-500">Connect calendars now, or choose <strong>Set up later</strong>. Verified Shortlet and manual bookings work without these links.</p></div>
<div class="mb-5 rounded-xl border border-orange-200 bg-orange-50 p-4"><h2 class="text-sm font-bold text-gray-900">Which link should I paste?</h2><p class="mt-1 text-sm leading-6 text-gray-600">Use the private <strong>calendar export / iCal link</strong> copied from the calendar settings inside Airbnb or Booking.com. It normally ends in <strong>.ics</strong> or contains <strong>ical</strong>. Do not paste your public listing or property page URL.</p></div>
@php $selected=$property->channelConnections->where('status','active')->pluck('provider')->all(); $connections=$property->externalCalendarConnections->keyBy('provider'); $channels=['airbnb'=>['Airbnb','Export calendar → Copy link','https://www.airbnb.com/calendar/ical/123456.ics?s=…'],'bookingcom'=>['Booking.com','Sync calendars → Export calendar → Copy link','https://admin.booking.com/hotel/hoteladmin/ical.html?t=…'],'whatsapp'=>['WhatsApp','Manual bookings from your business number.',null]]; @endphp
<section class="space-y-3"><div class="flex items-center gap-4 rounded-xl border border-orange-200 bg-white p-5"><span class="flex size-11 items-center justify-center rounded-xl bg-[#FF5A00] font-bold text-white">VS</span><div class="flex-1"><h2 class="font-bold">Verified Shortlet — Direct</h2><p class="mt-1 text-xs text-gray-500">Always enabled for marketplace bookings.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold text-emerald-700">ACTIVE</span></div>
@foreach($channels as $provider=>[$name,$description,$example])@php $externalConnection=$connections->get($provider); @endphp<div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm transition hover:border-orange-300"><label class="flex cursor-pointer items-center gap-4"><input type="checkbox" name="channels[]" value="{{ $provider }}" @checked(in_array($provider,$selected,true)) class="size-5 rounded border-gray-300 text-[#FF5A00] focus:ring-[#FF5A00]"><div class="flex-1"><h2 class="font-bold">{{ $name }}</h2><p class="mt-1 text-xs text-gray-500">{{ $description }}</p></div><span class="rounded-full {{ $externalConnection ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-600' }} px-3 py-1 text-[10px] font-bold">{{ $externalConnection ? strtoupper($externalConnection->sync_status) : 'SET UP LATER' }}</span></label>@if($example)<div class="mt-4 rounded-xl border border-gray-200 bg-gray-50 p-3"><label for="calendar-{{ $provider }}" class="mb-1.5 block text-xs font-bold text-gray-700">{{ $name }} calendar export URL <span class="font-normal text-gray-400">(optional)</span></label><div class="flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 focus-within:border-[#FF5A00] focus-within:ring-2 focus-within:ring-orange-100"><svg class="size-4 shrink-0 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg><input id="calendar-{{ $provider }}" type="url" name="calendar_urls[{{ $provider }}]" value="{{ old('calendar_urls.'.$provider, $externalConnection?->inboundFeedUrl()) }}" placeholder="{{ $example }}" class="block w-full border-0 bg-transparent px-0 py-2.5 text-sm focus:ring-0" aria-describedby="calendar-{{ $provider }}-help"></div><p id="calendar-{{ $provider }}-help" class="mt-2 text-xs text-gray-500">You can leave this blank and connect it later from the property details page.</p></div>@endif</div>@endforeach
<div class="flex items-center gap-4 rounded-xl border border-gray-200 bg-gray-50 p-5 opacity-70"><input type="checkbox" checked disabled class="size-5 rounded"><div class="flex-1"><h2 class="font-bold">Walk-in / Phone call</h2><p class="mt-1 text-xs text-gray-500">Always available for manual bookings.</p></div><span class="text-xs font-semibold text-gray-500">Always on</span></div></section>
<div class="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-gray-700"><strong>Two-way calendar setup:</strong> paste the provider's export link here first. After saving, open <strong>Property details → Calendar sync</strong>, copy your Verified Shortlet export URL, and paste it into the provider's calendar-import screen. No API key is required.</div>
<div class="mt-6 flex items-center justify-between"><a href="{{ route('owner.properties.wizard.step',['property'=>$property,'step'=>8]) }}" class="text-sm text-gray-500 underline">Back</a><div class="flex items-center gap-4"><button type="submit" formaction="{{ route('owner.properties.wizard.skip',['property'=>$property,'step'=>9]) }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-200">Set up later</button><button class="rounded-lg bg-[#FF5A00] px-8 py-2.5 text-sm font-bold text-white">Save & continue</button></div></div>
</form></main></div></body></html>
