@extends('layouts.app')
@section('content')
<x-navbar />
<main class="mx-auto max-w-4xl px-4 py-8 sm:px-6">
    <div class="flex items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-orange-600">Operations</p><h1 class="mt-1 text-3xl font-extrabold">My tasks</h1><p class="mt-2 text-sm text-slate-500">Only work assigned to you is shown here.</p></div><a href="{{ route('notifications.index') }}" class="rounded-xl border px-4 py-2 text-sm font-bold">Alerts</a></div>
    @if(session('status'))<div class="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <div class="mt-7 space-y-4">
        @forelse($tasks as $task)
            @php($overdue = $task->due_at?->isPast() && !in_array($task->status->value,['completed','cancelled']))
            <article class="overflow-hidden rounded-2xl border bg-white shadow-sm {{ $overdue ? 'border-red-300' : 'border-slate-200' }}">
                <div class="p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-bold uppercase text-orange-700">{{ str($task->task_type->value)->replace('_',' ') }}</span>@if($overdue)<span class="rounded-full bg-red-100 px-2.5 py-1 text-[10px] font-extrabold uppercase text-red-700">Overdue</span>@endif</div><h2 class="mt-2 text-lg font-extrabold">{{ $task->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $task->property->name }} · {{ $task->reference }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ str($task->status->value)->replace('_',' ')->title() }}</span></div>
                    <div class="mt-4 grid gap-3 rounded-xl bg-slate-50 p-3 text-xs sm:grid-cols-2"><div><span class="text-slate-400">Due</span><strong class="block mt-1 {{ $overdue?'text-red-700':'text-slate-800' }}">{{ $task->due_at?->format('d M Y, H:i') ?? 'No due time' }}</strong></div>@if($task->booking)<div><span class="text-slate-400">Stay window</span><strong class="mt-1 block">{{ $task->booking->arrival_date->format('d M') }} – {{ $task->booking->departure_date->format('d M Y') }}</strong></div>@endif</div>
                    @if($task->notes)<p class="mt-4 text-sm leading-6 text-slate-600">{{ $task->notes }}</p>@endif
                    @if($task->attachments->isNotEmpty())<div class="mt-4 flex flex-wrap gap-2">@foreach($task->attachments as $attachment)<a href="{{ route('task-attachments.show',[$task,$attachment]) }}" target="_blank" rel="noopener" class="rounded-lg border px-3 py-2 text-xs font-bold">{{ $attachment->original_name ?: 'View evidence' }}</a>@endforeach</div>@endif
                    @if($task->status->value==='assigned' || $task->status->value==='pending')<form method="POST" action="{{ route('staff.tasks.transition',$task) }}" class="mt-4">@csrf @method('PATCH')<input type="hidden" name="action" value="start"><button class="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Start task</button></form>@endif
                    @if($task->status->value==='in_progress' && $task->task_type->value==='inspection' && $task->booking_id)<form method="POST" enctype="multipart/form-data" action="{{ route('staff.tasks.inspection',$task) }}" class="mt-5 space-y-3">@csrf<label class="block text-xs font-bold">Result<select name="result" required class="mt-1 w-full rounded-xl border-slate-200"><option value="passed">Pass — property ready</option><option value="failed">Fail — corrective work needed</option></select></label><label class="block text-xs font-bold">Corrective action if failed<select name="corrective_action" class="mt-1 w-full rounded-xl border-slate-200"><option value="cleaning">Repeat cleaning</option><option value="maintenance">Maintenance</option></select></label><label class="block text-xs font-bold">Findings<textarea name="findings" rows="3" class="mt-1 w-full rounded-xl border-slate-200"></textarea></label><label class="block text-xs font-bold">Inspection evidence<input type="file" name="evidence[]" multiple accept="image/*" class="mt-1 block w-full rounded-xl border border-slate-200 bg-white p-2 text-sm"></label><button class="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Record inspection</button></form>@elseif($task->status->value==='in_progress')<form method="POST" enctype="multipart/form-data" action="{{ route('staff.tasks.transition',$task) }}" class="mt-5 space-y-3">@csrf @method('PATCH')<input type="hidden" name="action" value="complete">@foreach($task->checklistItems as $item)<label class="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" name="checklist_items[]" value="{{ $item->id }}" @checked($item->is_completed) class="mt-0.5 rounded border-slate-300 text-orange-600"><span>{{ $item->title }}@if($item->is_required)<small class="block text-slate-400">Required</small>@endif</span></label>@endforeach<label class="block text-xs font-bold">Before/after evidence<input type="file" name="evidence[]" multiple accept="image/*" class="mt-1 block w-full rounded-xl border border-slate-200 bg-white p-2 text-sm"></label><label class="block text-xs font-bold">Completion notes<textarea name="completion_notes" required rows="3" class="mt-1 w-full rounded-xl border-slate-200"></textarea></label><button class="w-full rounded-xl bg-orange-600 px-4 py-3 text-sm font-bold text-white">Complete task</button></form>@endif
                </div>
            </article>
        @empty<div class="rounded-2xl border border-dashed p-12 text-center text-slate-500">No tasks are assigned to you.</div>@endforelse
    </div>
    <div class="mt-6">{{ $tasks->links() }}</div>
</main>
@endsection
