<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $booking->reference }} – Booking</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false}"><div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'bookings'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><a href="{{ route('owner.bookings') }}" class="text-xs font-bold uppercase tracking-wider text-orange-600">← Bookings</a><h1 class="mt-1 text-xl font-extrabold">Booking details</h1></header>
<main class="mx-auto max-w-[1200px] px-4 py-6 lg:px-6">@if(session('status'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif @if($errors->any())<div class="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-bold">The booking could not be updated.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><div class="flex flex-col justify-between gap-4 border-b border-slate-100 pb-5 sm:flex-row"><div><p class="font-mono text-xs text-slate-400">{{ $booking->reference }}</p><h2 class="mt-2 text-2xl font-extrabold">{{ $booking->property->name }}</h2><p class="mt-2 text-sm text-slate-500">{{ $booking->arrival_date->format('d M Y') }} – {{ $booking->departure_date->format('d M Y') }}</p></div><div class="flex gap-2"><span class="h-fit rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{{ str($booking->status->value)->replace('_',' ')->title() }}</span><span class="h-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">{{ str($booking->payment_status->value)->replace('_',' ')->title() }}</span></div></div>
<div class="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Guest</h3><p class="mt-2 font-bold">{{ $booking->guest->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $booking->guest->email }}</p></div><div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Stay</h3><p class="mt-2 font-bold">{{ $booking->number_of_guests }} {{ Str::plural('guest',$booking->number_of_guests) }} · {{ $booking->arrival_date->diffInDays($booking->departure_date) }} nights</p><p class="mt-1 text-sm text-slate-500">{{ str($booking->source->value)->replace('_',' ')->title() }}</p></div><div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Total</h3><p class="mt-2 text-xl font-extrabold">{{ $booking->currency==='NGN'?'₦':$booking->currency.' ' }}{{ number_format((float)$booking->total_amount) }}</p><p class="mt-1 text-sm text-slate-500">{{ $booking->payments->count() }} payment {{ Str::plural('record',$booking->payments->count()) }}</p></div></div>
@if($booking->special_requests)<div class="mt-6 rounded-xl bg-slate-50 p-4"><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Special requests</h3><p class="mt-2 text-sm text-slate-700">{{ $booking->special_requests }}</p></div>@endif
</section>
@if(in_array($booking->status->value,['reserved','awaiting_payment','confirmed'],true))<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Change stay dates</h2><p class="mt-1 text-sm text-slate-500">The new dates are checked against bookings and manual calendar blocks before saving.</p><form method="POST" action="{{ route('owner.bookings.dates.update',$booking) }}" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1.5fr_auto] lg:items-end">@csrf @method('PATCH')<label class="text-xs font-bold text-slate-600">Arrival<input type="date" name="arrival_date" required value="{{ old('arrival_date',$booking->arrival_date->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Departure<input type="date" name="departure_date" required value="{{ old('departure_date',$booking->departure_date->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Reason<input type="text" name="reason" required maxlength="1000" value="{{ old('reason') }}" placeholder="Why are the dates changing?" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Update dates</button></form></section>@endif
@if($booking->dateChanges->isNotEmpty())<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Date-change history</h2><div class="mt-3 divide-y divide-slate-100">@foreach($booking->dateChanges as $change)<div class="py-3"><p class="text-sm font-bold">{{ $change->previous_arrival_date->format('d M Y') }} – {{ $change->previous_departure_date->format('d M Y') }} <span class="mx-1 text-slate-300">→</span> {{ $change->new_arrival_date->format('d M Y') }} – {{ $change->new_departure_date->format('d M Y') }}</p><p class="mt-1 text-xs text-slate-500">{{ $change->reason }} · {{ $change->occurred_at->format('d M Y, H:i') }}</p></div>@endforeach</div></section>@endif
</main></div></div></body></html>
