<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $booking->reference }} – Booking</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
@php
    $status = $booking->status->value;
    $steps = ['confirmed' => 'Confirmed', 'checked_in' => 'Checked in', 'checked_out' => 'Checked out', 'completed' => 'Completed'];
    $currentIndex = array_search($status, array_keys($steps), true);
    $paid = $booking->payments->filter(fn ($payment) => $payment->status->value === 'completed' && $payment->purpose->value !== 'refund')->sum('amount');
    $refunded = $booking->payments->filter(fn ($payment) => $payment->status->value === 'completed' && $payment->purpose->value === 'refund')->sum('amount');
    $outstanding = max(0,(float)$booking->total_amount-(float)$paid);
    $prepIncomplete = $booking->operationalTasks->filter(fn($task)=>in_array(data_get($task->generation_metadata,'workflow_stage'),['pre_arrival_cleaning','guest_welcome'],true) && $task->status->value!=='completed')->count();
    $timeline = collect();
    foreach($booking->statusHistory as $event) $timeline->push(['at'=>$event->occurred_at,'title'=>str($event->new_status)->replace('_',' ')->title(),'detail'=>$event->reason]);
    foreach($booking->payments as $payment) $timeline->push(['at'=>$payment->transaction_at,'title'=>$payment->purpose->value==='refund'?'Refund recorded':'Payment recorded','detail'=>$payment->currency.' '.number_format((float)$payment->amount).' · '.str($payment->status->value)->title()]);
    foreach($booking->dateChanges as $change) $timeline->push(['at'=>$change->occurred_at,'title'=>'Stay dates changed','detail'=>$change->reason]);
    foreach($booking->operationalTasks as $task) $timeline->push(['at'=>$task->completed_at ?: $task->started_at ?: $task->created_at,'title'=>$task->title,'detail'=>str($task->status->value)->replace('_',' ')->title()]);
    foreach($booking->serviceRequests as $request) $timeline->push(['at'=>$request->resolved_at ?: $request->requested_at,'title'=>str($request->request_type)->title().' service request','detail'=>str($request->status)->title().($request->resolution?' · '.$request->resolution:'')]);
    foreach($booking->reviews as $review) { $timeline->push(['at'=>$review->submitted_at,'title'=>'Verified-stay review submitted','detail'=>$review->rating.' stars'.($review->title?' · '.$review->title:'')]); if($review->response) $timeline->push(['at'=>$review->response->submitted_at,'title'=>'Owner responded to review','detail'=>$review->response->content]); }
    foreach($booking->cancellations as $cancel) $timeline->push(['at'=>$cancel->completed_at ?: $cancel->requested_at,'title'=>'Cancellation','detail'=>$cancel->reason ?: 'Cancellation processed']);
    $timeline=$timeline->filter(fn($row)=>$row['at'])->sortByDesc('at');
    $bookingPermissions = app(\App\Services\Access\BusinessPermissionService::class);
    $canModify = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'booking.modify', $booking->property);
    $canCancel = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'booking.cancel', $booking->property);
    $canCheckIn = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'booking.check_in', $booking->property);
    $canCheckOut = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'booking.check_out', $booking->property);
    $canCommunicate = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'booking.communicate', $booking->property);
    $canRespondToReviews = $bookingPermissions->allows(auth()->user(), $activeBusinessContext, 'property.respond_reviews', $booking->property);
@endphp
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false,checkInOpen:false,checkOutOpen:false,noShowOpen:false,cancelOpen:false}">
<div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'bookings'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><a href="{{ route('owner.bookings') }}" class="text-xs font-bold uppercase tracking-wider text-orange-600">← Bookings</a><h1 class="mt-1 text-xl font-extrabold">Booking workspace</h1></header>
<main class="mx-auto max-w-[1200px] px-4 py-6 lg:px-6">
    @if(session('status'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-bold">The booking could not be updated.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7">
        <div class="flex flex-col justify-between gap-4 border-b border-slate-100 pb-5 sm:flex-row">
            <div><p class="font-mono text-xs text-slate-400">{{ $booking->reference }}</p><h2 class="mt-2 text-2xl font-extrabold">{{ $booking->property->name }}</h2><p class="mt-2 text-sm text-slate-500">{{ $booking->arrival_date->format('d M Y') }} – {{ $booking->departure_date->format('d M Y') }}</p></div>
            <div class="flex flex-wrap items-start gap-2"><span class="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{{ str($status)->replace('_',' ')->title() }}</span><span class="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">{{ str($booking->payment_status->value)->replace('_',' ')->title() }}</span></div>
        </div>

        @if($currentIndex !== false)
            <div class="mt-6 grid grid-cols-4 gap-2" aria-label="Booking lifecycle">@foreach($steps as $key => $label)@php($index=$loop->index)<div class="text-center"><div class="h-2 rounded-full {{ $index <= $currentIndex ? 'bg-orange-500' : 'bg-slate-200' }}"></div><p class="mt-2 text-[10px] font-bold {{ $index <= $currentIndex ? 'text-orange-700' : 'text-slate-400' }}">{{ $label }}</p></div>@endforeach</div>
        @endif

        <div class="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Guest</h3><p class="mt-2 font-bold">{{ $booking->guest->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $booking->guest->email }}</p></div>
            <div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Stay</h3><p class="mt-2 font-bold">{{ $booking->number_of_guests }} {{ Str::plural('guest',$booking->number_of_guests) }} · {{ $booking->arrival_date->diffInDays($booking->departure_date) }} nights</p><p class="mt-1 text-sm text-slate-500">{{ str($booking->source->value)->replace('_',' ')->title() }}</p></div>
            <div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Finance</h3><p class="mt-2 text-xl font-extrabold">{{ $booking->currency==='NGN'?'₦':$booking->currency.' ' }}{{ number_format((float)$booking->total_amount) }}</p><p class="mt-1 text-sm text-slate-500">Paid ₦{{ number_format((float)$paid) }} · Refunded ₦{{ number_format((float)$refunded) }}</p><p class="mt-1 text-xs font-bold {{ $outstanding>0?'text-amber-700':'text-emerald-700' }}">Outstanding ₦{{ number_format($outstanding) }}</p></div>
            <div><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Quick actions</h3><div class="mt-2 flex flex-wrap gap-2">@if($status==='confirmed' && $canCheckIn)<button @click="checkInOpen=true" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Check in</button>@endif @if($status==='confirmed' && $canModify)<button @click="noShowOpen=true" class="rounded-lg border border-amber-300 px-3 py-2 text-xs font-bold text-amber-700">No-show</button>@endif @if($status==='checked_in' && $canCheckOut)<button @click="checkOutOpen=true" class="rounded-lg bg-orange-600 px-3 py-2 text-xs font-bold text-white">Check out</button>@endif @if(in_array($status,['reserved','awaiting_payment','confirmed'],true) && $canCancel)<button @click="cancelOpen=true" class="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Cancel booking</button>@endif @if(!($status==='confirmed' && ($canCheckIn || $canModify)) && !($status==='checked_in' && $canCheckOut) && !(in_array($status,['reserved','awaiting_payment','confirmed'],true) && $canCancel))<span class="text-sm text-slate-400">No permitted action required</span>@endif</div></div>
        </div>
        @if($booking->special_requests)<div class="mt-6 rounded-xl bg-slate-50 p-4"><h3 class="text-xs font-bold uppercase tracking-wider text-slate-400">Special requests</h3><p class="mt-2 text-sm text-slate-700">{{ $booking->special_requests }}</p></div>@endif
    </section>

    @if($canModify && in_array($status,['reserved','awaiting_payment','confirmed'],true))
        <section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Change stay dates</h2><p class="mt-1 text-sm text-slate-500">The new dates are checked against bookings and all availability blocks before saving.</p><form method="POST" action="{{ route('owner.bookings.dates.update',$booking) }}" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1.5fr_auto] lg:items-end">@csrf @method('PATCH')<label class="text-xs font-bold text-slate-600">Arrival<input type="date" name="arrival_date" required value="{{ old('arrival_date',$booking->arrival_date->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Departure<input type="date" name="departure_date" required value="{{ old('departure_date',$booking->departure_date->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-600">Reason<input type="text" name="reason" required maxlength="1000" value="{{ old('reason') }}" placeholder="Why are the dates changing?" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Update dates</button></form></section>
    @endif

    <div class="mt-5 grid gap-5 lg:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Operational work</h2><div class="mt-3 divide-y divide-slate-100">@forelse($booking->operationalTasks as $task)<div class="py-3"><div class="flex justify-between gap-3"><p class="text-sm font-bold">{{ $task->title }}</p><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{{ str($task->status->value)->replace('_',' ')->title() }}</span></div><p class="mt-1 text-xs text-slate-500">{{ str($task->task_type->value)->replace('_',' ')->title() }} · Due {{ optional($task->due_at)->format('d M Y, H:i') ?: 'not set' }}</p></div>@empty<p class="py-5 text-sm text-slate-500">No booking-linked operational tasks yet.</p>@endforelse</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Booking timeline</h2><div class="mt-3 border-l-2 border-slate-100 pl-4">@forelse($timeline as $event)<div class="relative pb-4"><span class="absolute -left-[21px] top-1 size-2.5 rounded-full bg-orange-500 ring-4 ring-white"></span><p class="text-sm font-bold">{{ $event['title'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $event['detail'] }} · {{ $event['at']->format('d M Y, H:i') }}</p></div>@empty<p class="py-5 text-sm text-slate-500">No lifecycle activity yet.</p>@endforelse</div></section>
    </div>

    @if($booking->serviceRequests->isNotEmpty())
        <section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Guest service requests</h2><div class="mt-3 grid gap-3 lg:grid-cols-2">
            @foreach($booking->serviceRequests->sortByDesc('requested_at') as $request)
                <article class="rounded-xl border p-4"><div class="flex justify-between gap-3"><div><p class="text-sm font-bold">{{ str($request->request_type)->title() }} · {{ str($request->priority)->title() }}</p><p class="mt-1 text-xs text-slate-400">{{ $request->requested_at->format('d M Y, H:i') }}</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase">{{ $request->status }}</span></div><p class="mt-3 text-sm text-slate-600">{{ $request->description }}</p>
                    @if($request->resolution)<p class="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800"><strong>Resolved:</strong> {{ $request->resolution }}</p>@endif
                    @if($canCommunicate && $request->status==='open')<form method="POST" action="{{ route('owner.service-requests.update',$request) }}" class="mt-3">@csrf @method('PATCH')<input type="hidden" name="action" value="acknowledge"><button class="rounded-lg border px-3 py-2 text-xs font-bold">Acknowledge</button></form>@endif
                    @if($canCommunicate && in_array($request->status,['open','acknowledged'],true))<form method="POST" action="{{ route('owner.service-requests.update',$request) }}" class="mt-3 flex gap-2">@csrf @method('PATCH')<input type="hidden" name="action" value="resolve"><input name="resolution" required maxlength="2000" placeholder="Resolution provided" class="min-w-0 flex-1 rounded-lg border-slate-200 text-xs"><button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Resolve</button></form>@endif
                </article>
            @endforeach
        </div></section>
    @endif

    @if($booking->reviews->isNotEmpty())
        <section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-extrabold uppercase tracking-[.14em] text-emerald-700">✓ Verified stay</p><h2 class="mt-2 text-lg font-extrabold">Guest review</h2></div><p class="text-xl font-extrabold text-orange-600">{{ str_repeat('★', $booking->reviews->first()->rating) }}<span class="text-orange-200">{{ str_repeat('★', 5 - $booking->reviews->first()->rating) }}</span></p></div>
            @php($review = $booking->reviews->first())
            <div class="mt-4 rounded-xl bg-slate-50 p-4"><div class="flex flex-wrap justify-between gap-3"><div><p class="font-extrabold">{{ $review->title ?: 'Guest feedback' }}</p><p class="mt-1 text-xs text-slate-400">{{ $review->guest->name }} · {{ $review->published_at->format('d M Y') }}</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Public</span></div><p class="mt-3 text-sm leading-6 text-slate-700">{{ $review->content }}</p></div>
            @if($review->response)
                <div class="mt-4 rounded-xl border border-orange-200 bg-orange-50 p-4"><p class="text-xs font-extrabold uppercase tracking-wide text-orange-700">Your public response</p><p class="mt-2 text-sm leading-6 text-slate-700">{{ $review->response->content }}</p></div>
            @elseif($canRespondToReviews)
                <form method="POST" action="{{ route('owner.reviews.responses.store', $review) }}" class="mt-4">@csrf<label class="block text-xs font-bold text-slate-700">Respond publicly<textarea name="content" required minlength="10" maxlength="2000" rows="4" placeholder="Thank the guest or address their feedback professionally" class="mt-2 w-full rounded-xl border-slate-200 text-sm">{{ old('content') }}</textarea></label><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><p class="text-xs text-slate-500">Your response appears beneath this review on the public listing.</p><button class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-extrabold text-white">Publish response</button></div></form>
            @endif
        </section>
    @endif

    @if($booking->dateChanges->isNotEmpty())<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><h2 class="text-base font-extrabold">Date-change history</h2><div class="mt-3 divide-y divide-slate-100">@foreach($booking->dateChanges as $change)<div class="py-3"><p class="text-sm font-bold">{{ $change->previous_arrival_date->format('d M Y') }} – {{ $change->previous_departure_date->format('d M Y') }} <span class="mx-1 text-slate-300">→</span> {{ $change->new_arrival_date->format('d M Y') }} – {{ $change->new_departure_date->format('d M Y') }}</p><p class="mt-1 text-xs text-slate-500">{{ $change->reason }} · {{ $change->occurred_at->format('d M Y, H:i') }}</p></div>@endforeach</div></section>@endif
</main></div></div>

@if($canCancel && in_array($status,['reserved','awaiting_payment','confirmed'],true))
<div x-show="cancelOpen" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button @click="cancelOpen=false" class="absolute inset-0 bg-slate-950/60" aria-label="Close cancellation dialog"></button><form method="POST" action="{{ route('owner.bookings.cancel',$booking) }}" class="relative w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl">@csrf<div class="flex size-11 items-center justify-center rounded-full bg-red-50 text-xl text-red-700">!</div><h2 class="mt-4 text-xl font-extrabold">Cancel this booking?</h2><p class="mt-2 text-sm text-slate-500">The guest will be notified, reserved dates will reopen, incomplete operational tasks will stop, and any captured simulated payment will be refunded.</p><label class="mt-5 block text-xs font-bold text-slate-700">Reason for cancellation<textarea name="reason" required maxlength="1000" rows="3" placeholder="Explain why this booking cannot proceed" class="mt-2 w-full rounded-xl border-slate-200 text-sm"></textarea></label><div class="mt-5 flex justify-end gap-2"><button type="button" @click="cancelOpen=false" class="rounded-lg border px-4 py-2 text-sm font-bold">Keep booking</button><button class="rounded-lg bg-red-600 px-4 py-2 text-sm font-bold text-white">Cancel & notify guest</button></div></form></div>
@endif

@if($canCheckIn && $status==='confirmed')
<div x-show="checkInOpen" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button @click="checkInOpen=false" class="absolute inset-0 bg-slate-950/60" aria-label="Close"></button><form method="POST" action="{{ route('owner.bookings.check-in',$booking) }}" class="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl">@csrf<h2 class="text-xl font-extrabold">Confirm guest check-in</h2><p class="mt-2 text-sm text-slate-500">Verify the essentials before handing over access.</p>@if($outstanding>0 || $prepIncomplete>0)<div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><strong>Check before continuing:</strong><ul class="mt-1 list-inside list-disc">@if($outstanding>0)<li>Outstanding balance: ₦{{ number_format($outstanding) }}</li>@endif @if($prepIncomplete>0)<li>{{ $prepIncomplete }} preparation {{ Str::plural('task',$prepIncomplete) }} incomplete</li>@endif</ul></div>@endif<div class="mt-5 grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold">Identity<select name="identity_status" class="mt-1 w-full rounded-lg border-slate-200"><option value="verified">Verified</option><option value="waived">Waived by owner</option></select></label><label class="text-xs font-bold">Balance<select name="balance_status" class="mt-1 w-full rounded-lg border-slate-200"><option value="paid">Paid</option><option value="approved_outstanding">Outstanding approved</option></select></label><label class="text-xs font-bold">Access method<input name="access_method" maxlength="40" placeholder="Keys / smart lock" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs font-bold">Access reference<input name="access_reference" maxlength="255" placeholder="Optional reference" class="mt-1 w-full rounded-lg border-slate-200"></label></div><textarea name="notes" maxlength="1000" rows="3" placeholder="Check-in notes" class="mt-3 w-full rounded-lg border-slate-200"></textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="checkInOpen=false" class="rounded-lg border px-4 py-2 text-sm font-bold">Not yet</button><button class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Complete check-in</button></div></form></div>
@endif
@if($canModify && $status==='confirmed')
<div x-show="noShowOpen" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button @click="noShowOpen=false" class="absolute inset-0 bg-slate-950/60" aria-label="Close"></button><form method="POST" action="{{ route('owner.bookings.no-show',$booking) }}" class="relative w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl">@csrf<h2 class="text-xl font-extrabold">Mark as no-show?</h2><p class="mt-2 text-sm text-slate-500">This releases active booking dates and cannot be undone.</p><textarea name="reason" maxlength="1000" rows="3" placeholder="Reason or contact attempts" class="mt-4 w-full rounded-lg border-slate-200"></textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="noShowOpen=false" class="rounded-lg border px-4 py-2 text-sm font-bold">Keep booking</button><button class="rounded-lg bg-amber-600 px-4 py-2 text-sm font-bold text-white">Confirm no-show</button></div></form></div>
@endif
@if($canCheckOut && $status==='checked_in')
<div x-show="checkOutOpen" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button @click="checkOutOpen=false" class="absolute inset-0 bg-slate-950/60" aria-label="Close"></button><form method="POST" action="{{ route('owner.bookings.check-out',$booking) }}" class="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl">@csrf<h2 class="text-xl font-extrabold">Complete guest checkout</h2><p class="mt-2 text-sm text-slate-500">Record the handover and property condition.</p><div class="mt-5 grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold">Access returned<select name="access_return_status" class="mt-1 w-full rounded-lg border-slate-200"><option value="returned">Returned</option><option value="not_applicable">Not applicable</option><option value="missing">Missing</option></select></label><label class="text-xs font-bold">Room condition<select name="room_condition" class="mt-1 w-full rounded-lg border-slate-200"><option value="requires_cleaning">Requires cleaning</option><option value="good">Good</option><option value="damage_reported">Damage reported</option></select></label><label class="text-xs font-bold sm:col-span-2">Damage status<select name="damage_status" class="mt-1 w-full rounded-lg border-slate-200"><option value="none">No damage</option><option value="reported">Damage reported</option></select></label></div><textarea name="damage_notes" maxlength="2000" rows="2" placeholder="Damage notes, if applicable" class="mt-3 w-full rounded-lg border-slate-200"></textarea><textarea name="handover_notes" maxlength="2000" rows="3" placeholder="Checkout and handover notes" class="mt-3 w-full rounded-lg border-slate-200"></textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="checkOutOpen=false" class="rounded-lg border px-4 py-2 text-sm font-bold">Not yet</button><button class="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white">Complete checkout</button></div></form></div>
@endif
</body></html>
