@extends('layouts.admin', ['title' => 'Audit history', 'pageTitle' => 'Audit history'])

@section('content')
<div class="mx-auto max-w-7xl space-y-5">
    <div><p class="text-sm font-semibold text-slate-500">A read-only history of sensitive platform and business actions.</p><p class="mt-1 text-xs text-slate-400">{{ number_format($events->total()) }} immutable events</p></div>
    <form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[1fr_13rem_13rem_13rem_auto]"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search descriptions or events" class="rounded-xl border-slate-200 text-sm"><select name="event" class="rounded-xl border-slate-200 text-sm"><option value="">All event types</option>@foreach($eventTypes as $event)<option value="{{ $event }}" @selected(($filters['event']??'')===$event)>{{ str($event)->replace('.',' ')->title() }}</option>@endforeach</select><select name="administrator" class="rounded-xl border-slate-200 text-sm"><option value="">All administrators</option>@foreach($administrators as $administrator)<option value="{{ $administrator->id }}" @selected(($filters['administrator']??'')===$administrator->id)>{{ $administrator->name }}</option>@endforeach</select><select name="business" class="rounded-xl border-slate-200 text-sm"><option value="">All businesses</option>@foreach($businesses as $business)<option value="{{ $business->id }}" @selected(($filters['business']??'')===$business->id)>{{ $business->name }}</option>@endforeach</select><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Apply filters</button></form>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="divide-y divide-slate-100">@forelse($events as $event)<article class="grid gap-3 px-5 py-5 sm:grid-cols-[1fr_auto]"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-700">{{ str($event->event_type)->replace('.',' ')->title() }}</span>@if($event->business)<span class="text-xs font-bold text-orange-600">{{ $event->business->name }}</span>@endif</div><p class="mt-3 text-sm font-black text-slate-900">{{ $event->description }}</p>@if(data_get($event->metadata,'reason'))<p class="mt-1 text-sm text-slate-600">Reason: {{ data_get($event->metadata,'reason') }}</p>@endif<div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400"><span>Actor: {{ $event->actor?->name ?? 'System' }}</span><span>Subject: {{ class_basename($event->auditable_type) }} / {{ Str::limit($event->auditable_id,12,'…') }}</span><span>IP: {{ $event->ip_address ?: 'not recorded' }}</span></div></div><time class="text-xs font-semibold text-slate-400">{{ $event->occurred_at?->format('d M Y, H:i:s') }}</time></article>@empty<div class="p-12 text-center"><p class="font-bold text-slate-700">No audit events match these filters.</p><p class="mt-1 text-sm text-slate-500">Try widening the date, event or business criteria.</p></div>@endforelse</div></section>{{ $events->links() }}
</div>
@endsection
