@php
    $steps = ['basics' => 'Basics', 'amenities' => 'Amenities', 'media' => 'Media', 'house-rules' => 'House rules', 'operations' => 'Operations', 'assets' => 'Assets', 'documents' => 'Documents', 'marketplace' => 'Marketplace', 'review' => 'Review'];
    $keys = array_keys($steps);
    $previous = $keys[$stepNumber - 2] ?? null;
    $previousRoute = $previous === 'basics' ? 'owner.properties.edit' : ($previous ? 'owner.properties.setup.'.$previous : null);
    $storeRoute = 'owner.properties.setup.'.$step.'.store';
    $optional = in_array($step, ['amenities', 'house-rules', 'operations', 'assets', 'documents', 'marketplace'], true);
@endphp
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $steps[$step] }} – {{ $property->name }}</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased">
<div class="flex min-h-screen">@include('partials.sidebar-nav', ['active' => 'properties'])
<div class="min-w-0 flex-1">
    <header class="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur">
        <div class="flex items-center justify-between px-5 py-4 lg:px-8"><div><p class="text-xs font-bold text-slate-500">{{ $property->name }}</p><h1 class="mt-1 text-lg font-extrabold">{{ $steps[$step] }}</h1></div><a href="{{ route('owner.dashboard') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50">Exit setup</a></div>
        <div class="border-t border-slate-100 px-5 py-3 lg:px-8"><div class="mb-2 flex justify-between text-xs"><span class="font-extrabold text-orange-600">Step {{ $stepNumber }} of 9 · {{ $steps[$step] }}</span><span class="text-slate-400">{{ $stepNumber < 9 ? 'Next: '.$steps[$keys[$stepNumber]] : 'Final review' }}</span></div><div class="h-1.5 rounded-full bg-slate-100"><div class="h-full rounded-full bg-orange-600" style="width: {{ ($stepNumber / 9) * 100 }}%"></div></div></div>
    </header>
    <main class="mx-auto max-w-5xl px-5 py-8 lg:px-8 lg:py-10">
        @if (session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><p class="font-extrabold">Please review this step.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        @if ($step === 'house-rules')
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Set clear expectations</h2><p class="mt-2 text-sm text-slate-600">Add one rule per line. You can skip this and return later.</p></div>
            <form method="POST" action="{{ route($storeRoute, $property) }}">@csrf<section class="property-form-section p-6 sm:p-8"><label class="property-form-label">House rules<textarea name="rules" rows="9" class="property-form-control mt-2" placeholder="No smoking&#10;No parties or events&#10;Quiet hours begin at 10 PM">{{ old('rules', $property->houseRules->pluck('description')->join("\n")) }}</textarea></label></section>@include('owner.properties.partials.setup-actions')</form>
        @elseif ($step === 'operations')
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Prepare property operations</h2><p class="mt-2 text-sm text-slate-600">Set the default cleaning rhythm. Detailed staffing can be added later.</p></div>
            @php($schedule = $property->cleaningSchedules->first())
            <form method="POST" action="{{ route($storeRoute, $property) }}">@csrf<section class="property-form-section grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><label class="property-form-label">Cleaning frequency<select name="frequency" class="property-form-control mt-2">@foreach(['between_stays'=>'Between stays','daily'=>'Daily','weekly'=>'Weekly','monthly'=>'Monthly','custom'=>'Custom'] as $value=>$label)<option value="{{ $value }}" @selected(old('frequency', $schedule?->frequency?->value) === $value)>{{ $label }}</option>@endforeach</select></label><label class="property-form-label">Preferred start time<input type="time" name="preferred_start_time" value="{{ old('preferred_start_time', $schedule?->preferred_start_time) }}" class="property-form-control mt-2"></label><label class="property-form-label sm:col-span-2">Instructions<textarea name="instructions" rows="5" class="property-form-control mt-2">{{ old('instructions', $schedule?->instructions) }}</textarea></label></section>@include('owner.properties.partials.setup-actions')</form>
        @elseif ($step === 'assets')
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Record a key property asset</h2><p class="mt-2 text-sm text-slate-600">Add the first important asset now, or skip and build the inventory later.</p></div>
            @if($property->assets->isNotEmpty())<div class="mb-5 rounded-xl border border-slate-200 bg-white p-4 text-sm"><strong>{{ $property->assets->count() }} saved:</strong> {{ $property->assets->pluck('name')->join(', ') }}</div>@endif
            <form method="POST" action="{{ route($storeRoute, $property) }}">@csrf<section class="property-form-section grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><label class="property-form-label">Asset name<input name="name" value="{{ old('name') }}" class="property-form-control mt-2" placeholder="e.g. Living room television"></label><label class="property-form-label">Category<input name="category" value="{{ old('category') }}" class="property-form-control mt-2" placeholder="Electronics"></label><label class="property-form-label">Serial number <span class="property-form-optional">(optional)</span><input name="serial_number" value="{{ old('serial_number') }}" class="property-form-control mt-2"></label><label class="property-form-label">Condition<select name="condition" class="property-form-control mt-2">@foreach(['new','good','fair','poor','damaged'] as $condition)<option value="{{ $condition }}">{{ str($condition)->title() }}</option>@endforeach</select></label><label class="property-form-label">Replacement value <span class="property-form-optional">(optional)</span><input type="number" min="0" step="0.01" name="replacement_value" class="property-form-control mt-2"></label></section>@include('owner.properties.partials.setup-actions')</form>
        @elseif ($step === 'documents')
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Keep property documents together</h2><p class="mt-2 text-sm text-slate-600">Upload one supporting record now, or skip until verification requires it.</p></div>
            @if($property->documents->isNotEmpty())<div class="mb-5 rounded-xl border border-slate-200 bg-white p-4 text-sm"><strong>{{ $property->documents->count() }} saved:</strong> {{ $property->documents->pluck('title')->join(', ') }}</div>@endif
            <form method="POST" enctype="multipart/form-data" action="{{ route($storeRoute, $property) }}">@csrf<section class="property-form-section grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><label class="property-form-label">Document title<input name="title" value="{{ old('title') }}" class="property-form-control mt-2" placeholder="Property certificate"></label><label class="property-form-label">Category<select name="category" class="property-form-control mt-2">@foreach(['property_certificate'=>'Property certificate','insurance'=>'Insurance','tenancy_agreement'=>'Tenancy agreement','other'=>'Other'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="property-form-label sm:col-span-2">Choose file<input type="file" name="document" class="property-form-control mt-2" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></label></section>@include('owner.properties.partials.setup-actions')</form>
        @elseif ($step === 'marketplace')
            @php($listing = $property->marketplaceListing)
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Prepare the guest-facing listing</h2><p class="mt-2 text-sm text-slate-600">This information is required before verification submission.</p></div>
            <form method="POST" action="{{ route($storeRoute, $property) }}">@csrf<section class="property-form-section grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><label class="property-form-label sm:col-span-2">Public title<input name="public_title" value="{{ old('public_title', $listing?->public_title ?? $property->name) }}" class="property-form-control mt-2"></label><label class="property-form-label sm:col-span-2">Short summary<input name="short_summary" value="{{ old('short_summary', $listing?->short_summary) }}" class="property-form-control mt-2"></label><label class="property-form-label sm:col-span-2">Public description<textarea name="public_description" rows="7" class="property-form-control mt-2">{{ old('public_description', $listing?->public_description ?? $property->description) }}</textarea></label><label class="property-form-label">Check-in time<input type="time" name="check_in_time" value="{{ old('check_in_time', $listing?->check_in_time) }}" class="property-form-control mt-2"></label><label class="property-form-label">Check-out time<input type="time" name="check_out_time" value="{{ old('check_out_time', $listing?->check_out_time) }}" class="property-form-control mt-2"></label><label class="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="instant_booking_enabled" value="1" @checked(old('instant_booking_enabled', $listing?->instant_booking_enabled)) class="size-4 rounded text-orange-600">Enable instant booking</label></section>@include('owner.properties.partials.setup-actions')</form>
        @else
            <div class="mb-6"><h2 class="text-3xl font-extrabold">Review and complete setup</h2><p class="mt-2 text-sm text-slate-600">Completing setup activates the property inside your business. Public marketplace verification remains optional and separate.</p></div>
            <div class="grid gap-6 lg:grid-cols-2"><section class="property-form-section p-6"><h3 class="font-extrabold">Setup progress</h3><div class="mt-4 space-y-3">@foreach($property->setupSteps->sortBy('sort_order') as $progress)<div class="flex justify-between text-sm"><span>{{ $steps[$progress->step_key] }}</span><span class="font-bold {{ $progress->state === 'completed' ? 'text-emerald-600' : ($progress->state === 'skipped' ? 'text-amber-600' : 'text-slate-400') }}">{{ str($progress->state)->title() }}</span></div>@endforeach</div></section><section class="property-form-section p-6"><h3 class="font-extrabold">Readiness</h3>@if($blockers === [])<p class="mt-4 text-sm font-semibold text-emerald-700">All required publishing information is ready for verification.</p>@else<ul class="mt-4 space-y-2 text-sm text-red-700">@foreach($blockers as $blocker)<li>• {{ $blocker }}</li>@endforeach</ul>@endif @if($warnings !== [])<h4 class="mt-5 text-xs font-extrabold uppercase text-amber-700">Recommendations</h4><ul class="mt-2 space-y-1 text-sm text-amber-800">@foreach($warnings as $warning)<li>• {{ $warning }}</li>@endforeach</ul>@endif</section></div>
            <div class="mt-6 flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 shadow-lg">@if($previousRoute)<a href="{{ route($previousRoute, $property) }}" class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Back</a>@endif<form method="POST" action="{{ route('owner.properties.setup.review.complete', $property) }}">@csrf<button @disabled($blockers !== []) class="rounded-xl bg-orange-600 px-6 py-3 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:bg-slate-300">Complete property setup</button></form></div>
        @endif
    </main>
</div></div>
</body></html>
