@extends('layouts.admin', ['title' => $business->name, 'pageTitle' => 'Business oversight'])

@section('content')
@php
    $verification=$business->verification_status->value;
    $state=$business->status->value;
    $permissions=app(\App\Services\PlatformPermissionService::class);
    $canVerify=$permissions->allows(auth()->user(),'platform.business.verify');
    $canManage=$permissions->allows(auth()->user(),'platform.business.manage');
@endphp
<div class="mx-auto max-w-7xl space-y-5" x-data="{ action: null }">
    <a href="{{ route('admin.businesses.index') }}" class="inline-flex text-sm font-black text-orange-600">← Business directory</a>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
        <div class="flex flex-col justify-between gap-5 lg:flex-row">
            <div><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">{{ str($business->business_type)->replace('_',' ')->title() }}</p><h2 class="mt-2 text-3xl font-black">{{ $business->name }}</h2><div class="mt-3 flex flex-wrap gap-2"><span class="rounded-full px-3 py-1 text-xs font-black {{ $verification==='verified'?'bg-emerald-100 text-emerald-800':($verification==='rejected'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800') }}">{{ str($verification)->title() }}</span><span class="rounded-full px-3 py-1 text-xs font-black {{ $state==='active'?'bg-sky-100 text-sky-800':'bg-red-100 text-red-800' }}">{{ str($state)->title() }}</span></div></div>
            <div class="flex flex-wrap items-start gap-2">@if($canVerify && $verification!=='verified')<button @click="action='verify'" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Verify</button>@endif @if($canVerify && $verification!=='rejected')<button @click="action='reject'" class="rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-black text-red-700">Reject</button>@endif @if($canManage) @if($state==='suspended')<button @click="action='reactivate'" class="rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-black text-white">Reactivate</button>@else<button @click="action='suspend'" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Suspend</button>@endif @endif</div>
        </div>
        @if($state==='suspended')<div class="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>New activity is restricted.</strong> Marketplace discovery, new bookings and non-essential owner mutations are blocked. Existing stay completion remains available.</div>@endif
        <dl class="mt-7 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs font-bold text-slate-500">Registration</dt><dd class="mt-1 font-black">{{ $business->registration_number ?: 'Not provided' }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Primary contact</dt><dd class="mt-1 font-black">{{ $business->primary_contact_name ?: 'Not provided' }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Email</dt><dd class="mt-1 truncate font-black">{{ $business->email ?: 'Not provided' }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Location</dt><dd class="mt-1 font-black">{{ data_get($business->address,'city') ?: $business->country_code }}</dd></div></dl>
    </section>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Properties',$business->properties_count],['Team',$business->memberships_count],['Bookings',$business->bookings_count],['Payments',$business->payments_count],['Reviews',$reviewCount],['Disputes',$disputeCount]] as [$label,$value])<article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-black">{{ number_format($value) }}</p></article>@endforeach</section>

    <div class="grid gap-5 xl:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Property portfolio</h3></div><div class="divide-y divide-slate-100">@forelse($business->properties as $property)<a href="{{ route('admin.properties.show',$property) }}" class="flex items-center justify-between gap-4 px-5 py-4 hover:bg-slate-50"><div><p class="text-sm font-black">{{ $property->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $property->code }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{{ str($property->publication_status->value)->title() }}</span></a>@empty<div class="p-8 text-center text-sm text-slate-500">No properties yet.</div>@endforelse</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Team and access</h3></div><div class="divide-y divide-slate-100">@forelse($business->memberships->take(12) as $membership)<div class="px-5 py-4"><p class="text-sm font-black">{{ $membership->user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $membership->user->email }} · {{ $membership->roles->map(fn($assignment)=>$assignment->role?->name)->filter()->join(', ') ?: 'No active role' }}</p></div>@empty<div class="p-8 text-center text-sm text-slate-500">No team memberships.</div>@endforelse</div></section>
    </div>

    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Administrative history</h3></div><div class="divide-y divide-slate-100">@forelse($audits as $event)<div class="grid gap-1 px-5 py-4 sm:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold">{{ $event->description }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name ?? 'System' }} · {{ data_get($event->metadata,'reason') }}</p></div><time class="text-xs text-slate-400">{{ $event->occurred_at?->format('d M Y, H:i') }}</time></div>@empty<div class="p-8 text-center text-sm text-slate-500">No administrative decisions recorded.</div>@endforelse</div></section>

    @if($canVerify || $canManage)<div x-cloak x-show="action" class="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm" @keydown.escape.window="action=null"><div class="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" @click.outside="action=null"><div class="flex justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-widest text-orange-600">Administrative decision</p><h3 class="mt-2 text-xl font-black" x-text="action ? action.charAt(0).toUpperCase()+action.slice(1)+' this business?' : ''"></h3></div><button @click="action=null" class="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div><p class="mt-3 text-sm text-slate-600">This action is permanent in audit history. Explain the evidence or operational reason.</p><form method="POST" :action="'{{ url('/admin/businesses/'.$business->id) }}/'+action" class="mt-5">@csrf<textarea name="reason" required minlength="10" maxlength="1000" rows="4" class="block w-full rounded-xl border-slate-200 text-sm focus:border-orange-400 focus:ring-orange-200" placeholder="Enter a clear decision reason…">{{ old('reason') }}</textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="action=null" class="rounded-xl px-4 py-2.5 text-sm font-black text-slate-600">Cancel</button><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Confirm action</button></div></form></div></div>@endif
</div>
@endsection
