<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Bookings – {{ $business->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false}">
<div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'bookings'])
<div class="min-w-0 flex-1">
    <header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><div class="flex items-center gap-3"><button @click="sidebarOpen=true" class="rounded-lg p-2 md:hidden" aria-label="Open navigation">☰</button><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">{{ $business->name }}</p><h1 class="mt-1 text-xl font-extrabold">Bookings</h1></div></div></header>
    <main class="mx-auto max-w-[1600px] px-4 py-6 lg:px-6">
        @php($cards=[['Total bookings',$stats['total']],['Confirmed',$stats['confirmed']],['Pending',$stats['pending']],['Cancelled',$stats['cancelled']],['Check-ins today',$stats['check_ins']],['Check-outs today',$stats['check_outs']]])
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">@foreach($cards as [$label,$value])<div class="rounded-xl border border-slate-200 bg-white p-4"><p class="text-2xl font-extrabold">{{ $value }}</p><p class="mt-1 text-xs text-slate-500">{{ $label }}</p></div>@endforeach</div>

        <form method="GET" class="mt-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5">
            <input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Guest, property or reference" class="rounded-lg border-slate-200 text-sm lg:col-span-2">
            <select name="property" class="rounded-lg border-slate-200 text-sm"><option value="">All properties</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected(($filters['property']??'')===$property->id)>{{ $property->name }}</option>@endforeach</select>
            <select name="status" class="rounded-lg border-slate-200 text-sm"><option value="">All statuses</option>@foreach(['confirmed'=>'Confirmed','awaiting_payment'=>'Awaiting payment','reserved'=>'Reserved','checked_in'=>'Checked in','completed'=>'Completed','cancelled'=>'Cancelled'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select>
            <select name="channel" class="rounded-lg border-slate-200 text-sm"><option value="">All channels</option>@foreach(['marketplace'=>'Verified Shortlet','walk_in'=>'Walk-in','whatsapp'=>'WhatsApp','manual'=>'Manual','airbnb'=>'Airbnb','booking_dot_com'=>'Booking.com'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['channel']??'')===$value)>{{ $label }}</option>@endforeach</select>
            <input type="date" name="from" value="{{ $filters['from'] ?? '' }}" aria-label="Bookings from" class="rounded-lg border-slate-200 text-sm">
            <input type="date" name="to" value="{{ $filters['to'] ?? '' }}" aria-label="Bookings to" class="rounded-lg border-slate-200 text-sm">
            <select name="sort" class="rounded-lg border-slate-200 text-sm"><option value="newest">Newest first</option><option value="arrival" @selected(($filters['sort']??'')==='arrival')>Arrival date</option></select>
            <div class="flex gap-2"><button class="flex-1 rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Apply filters</button><a href="{{ route('owner.bookings') }}" class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold text-slate-600">Reset</a></div>
        </form>

        <section class="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white">
            @if($bookings->isEmpty())<div class="px-6 py-14 text-center"><h2 class="font-extrabold">No bookings found</h2><p class="mt-2 text-sm text-slate-500">Try changing your filters or wait for a new marketplace booking.</p></div>@else
            <div class="overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead class="border-b bg-slate-50 text-left text-[11px] uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Guest</th><th class="px-3 py-3">Property</th><th class="px-3 py-3">Dates</th><th class="px-3 py-3">Channel</th><th class="px-3 py-3">Status</th><th class="px-3 py-3">Amount</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
            @foreach($bookings as $booking)<tr class="hover:bg-slate-50"><td class="px-5 py-4"><p class="font-bold">{{ $booking->guest->name }}</p><p class="text-xs text-slate-400">{{ $booking->reference }}</p></td><td class="px-3 py-4"><p class="font-semibold">{{ $booking->property->name }}</p><p class="text-xs text-slate-400">{{ data_get($booking->property->address,'city') }}, {{ data_get($booking->property->address,'state') }}</p></td><td class="px-3 py-4 whitespace-nowrap">{{ $booking->arrival_date->format('j M Y') }} – {{ $booking->departure_date->format('j M Y') }}<p class="text-xs text-slate-400">{{ $booking->arrival_date->diffInDays($booking->departure_date) }} nights</p></td><td class="px-3 py-4">{{ str($booking->source->value)->replace('_',' ')->title() }}</td><td class="px-3 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{{ str($booking->status->value)->replace('_',' ')->title() }}</span></td><td class="px-3 py-4 font-bold">{{ $booking->currency==='NGN'?'₦':$booking->currency.' ' }}{{ number_format((float)$booking->total_amount) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('owner.bookings.show',$booking) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:bg-slate-50">View details</a></td></tr>@endforeach
            </tbody></table></div><div class="border-t px-5 py-3">{{ $bookings->links() }}</div>@endif
        </section>
        <p class="mt-4 text-xs text-slate-400">Manual owner bookings are not enabled in this release. Marketplace bookings appear here automatically.</p>
    </main>
</div></div></body></html>
