<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Finance – {{ $business->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false,expenseOpen:false,paymentOpen:false}"><div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'finance'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">{{ $business->name }}</p><h1 class="mt-1 text-xl font-extrabold">Finance</h1></div><div class="flex gap-2"><button @click="paymentOpen=!paymentOpen" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Record payment</button><button @click="expenseOpen=!expenseOpen" class="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white">Add expense</button></div></div></header>
<main class="mx-auto max-w-[1600px] space-y-5 px-4 py-6 lg:px-6">
@if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-bold">Please correct the finance entry.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-[1.5fr_1fr_1fr_1fr_1fr_auto]"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search transactions" class="rounded-lg border-slate-200 text-sm"><select name="property" class="rounded-lg border-slate-200 text-sm"><option value="">All properties</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected(($filters['property']??null)===$property->id)>{{ $property->name }}</option>@endforeach</select><select name="type" class="rounded-lg border-slate-200 text-sm"><option value="">All types</option>@foreach(['payment','refund','expense'] as $type)<option value="{{ $type }}" @selected(($filters['type']??null)===$type)>{{ str($type)->title() }}</option>@endforeach</select><input type="date" name="from" value="{{ $filters['from']??'' }}" class="rounded-lg border-slate-200 text-sm"><input type="date" name="to" value="{{ $filters['to']??'' }}" class="rounded-lg border-slate-200 text-sm"><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Apply</button></form>

@php($symbol=$currency==='NGN'?'₦':$currency.' ')
<section class="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">@foreach([['Revenue',$totals['revenue'],'text-emerald-700'],['Refunds',$totals['refunds'],'text-amber-700'],['Expenses',$totals['expenseTotal'],'text-red-700'],['Net income',$totals['net'],$totals['net']>=0?'text-slate-950':'text-red-700'],['Pending payments',$totals['pending'],'text-blue-700']] as [$label,$amount,$color])<div class="rounded-xl border border-slate-200 bg-white p-4"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-extrabold {{ $color }}">{{ $symbol }}{{ number_format($amount,2) }}</p></div>@endforeach</section>

<section x-show="paymentOpen" x-cloak class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-extrabold">Record a manual payment</h2><p class="mt-1 text-xs text-slate-500">For verified cash or bank payments. Gateway connection remains pending.</p><form method="POST" action="{{ route('owner.finance.payments.store') }}" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">@csrf<select name="booking_id" required class="rounded-lg border-slate-200 text-sm"><option value="">Select booking</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}">{{ $booking->reference }} · {{ $booking->property->name }}</option>@endforeach</select><input name="reference" required placeholder="Payment reference" class="rounded-lg border-slate-200 text-sm"><input type="number" step="0.0001" min="0.0001" name="amount" required placeholder="Amount" class="rounded-lg border-slate-200 text-sm"><select name="method" required class="rounded-lg border-slate-200 text-sm"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="wallet">Wallet</option></select><input type="datetime-local" name="transaction_at" required value="{{ now()->format('Y-m-d\TH:i') }}" class="rounded-lg border-slate-200 text-sm"><input name="notes" placeholder="Notes (optional)" class="rounded-lg border-slate-200 text-sm md:col-span-2 xl:col-span-4"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Save payment</button></form></section>

<section x-show="expenseOpen" x-cloak class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-extrabold">Add an expense</h2><form method="POST" enctype="multipart/form-data" action="{{ route('owner.finance.expenses.store') }}" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6">@csrf<select name="property_id" class="rounded-lg border-slate-200 text-sm"><option value="">General business expense</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select><select name="category" required class="rounded-lg border-slate-200 text-sm">@foreach(['cleaning','maintenance','utilities','supplies','staff','commission','other'] as $category)<option value="{{ $category }}">{{ str($category)->title() }}</option>@endforeach</select><input type="number" step="0.0001" min="0.0001" name="amount" required placeholder="Amount" class="rounded-lg border-slate-200 text-sm"><input type="date" name="incurred_on" required value="{{ now()->toDateString() }}" class="rounded-lg border-slate-200 text-sm"><input name="payee" placeholder="Payee (optional)" class="rounded-lg border-slate-200 text-sm"><input name="description" required placeholder="Description" class="rounded-lg border-slate-200 text-sm"><label class="text-xs font-bold text-slate-600 md:col-span-2">Receipt (optional)<input type="file" name="receipt" accept=".pdf,.jpg,.jpeg,.png,.webp" class="mt-1 block w-full text-sm"></label><button class="rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-bold text-white xl:col-start-6">Save expense</button></form></section>

<div class="grid gap-5 lg:grid-cols-2"><section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="text-sm font-extrabold">Revenue by property</h2><div class="mt-4 space-y-3">@forelse($revenueByProperty as $row)<div class="flex justify-between gap-4 text-sm"><span class="truncate text-slate-600">{{ $row['name'] }}</span><strong>{{ $symbol }}{{ number_format($row['amount'],2) }}</strong></div>@empty<p class="text-sm text-slate-500">No completed revenue in this period.</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="text-sm font-extrabold">Expenses by category</h2><div class="mt-4 space-y-3">@forelse($expensesByCategory as $row)<div class="flex justify-between gap-4 text-sm"><span class="text-slate-600">{{ $row['name'] }}</span><strong>{{ $symbol }}{{ number_format($row['amount'],2) }}</strong></div>@empty<p class="text-sm text-slate-500">No expenses in this period.</p>@endforelse</div></section></div>

<section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 p-5"><h2 class="text-sm font-extrabold">Transaction history</h2><p class="mt-1 text-xs text-slate-500">Real payment, refund and expense records.</p></div><div class="overflow-x-auto"><table class="min-w-[800px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Property</th><th class="px-5 py-3">Type</th><th class="px-5 py-3">Description</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($transactions as $row)<tr><td class="whitespace-nowrap px-5 py-3">{{ $row['date']->format('d M Y') }}</td><td class="px-5 py-3">{{ $row['property'] }}</td><td class="px-5 py-3 font-semibold">{{ str($row['type'])->title() }}</td><td class="px-5 py-3 text-slate-600">{{ $row['description'] }}</td><td class="px-5 py-3">{{ str($row['status'])->title() }}</td><td class="px-5 py-3 text-right font-bold {{ $row['positive']?'text-emerald-700':'text-red-700' }}">{{ $row['positive']?'+':'-' }}{{ $symbol }}{{ number_format($row['amount'],2) }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">No finance records match these filters.</td></tr>@endforelse</tbody></table></div></section>
</main></div></div></body></html>
