<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Operations – {{ $business->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
@php
    $operationPermissions = app(\App\Services\Access\BusinessPermissionService::class);
    $canAssignTasks = $operationPermissions->allows(auth()->user(), $activeBusinessContext, 'task.assign');
    $canReassignTasks = $operationPermissions->allows(auth()->user(), $activeBusinessContext, 'task.reassign');
    $canCompleteTasks = $operationPermissions->allows(auth()->user(), $activeBusinessContext, 'task.complete');
    $canInspect = $operationPermissions->allows(auth()->user(), $activeBusinessContext, 'inspection.perform');
@endphp
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false,createOpen:false}"><div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'operations'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><div class="flex items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">{{ $business->name }}</p><h1 class="mt-1 text-xl font-extrabold">Operations</h1></div>@if($canAssignTasks)<button @click="createOpen=!createOpen" class="rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-bold text-white">New task</button>@endif</div></header>
<main class="mx-auto max-w-[1600px] space-y-5 px-4 py-6 lg:px-6">
@if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<section class="grid grid-cols-2 gap-3 md:grid-cols-4">@foreach([['Open tasks',$stats['open']],['Urgent',$stats['urgent']],['In progress',$stats['inProgress']],['Completed',$stats['completed']]] as [$label,$value])<div class="rounded-xl border border-slate-200 bg-white p-4"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-extrabold">{{ $value }}</p></div>@endforeach</section>

@if($canAssignTasks)<section x-show="createOpen" x-cloak class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-extrabold">Create operational task</h2><form method="POST" action="{{ route('owner.operations.tasks.store') }}" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6">@csrf<select name="property_id" required class="rounded-lg border-slate-200 text-sm"><option value="">Select property</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select><input name="title" required placeholder="Task title" class="rounded-lg border-slate-200 text-sm"><select name="task_type" class="rounded-lg border-slate-200 text-sm">@foreach(['cleaning','maintenance','inspection','inventory_check','guest_welcome','photography','deep_cleaning','repair'] as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select><select name="priority" class="rounded-lg border-slate-200 text-sm">@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}">{{ str($priority)->title() }}</option>@endforeach</select><select name="assigned_employee_id" class="rounded-lg border-slate-200 text-sm"><option value="">Unassigned</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->businessMembership->user->name }}</option>@endforeach</select><input type="datetime-local" name="due_at" required class="rounded-lg border-slate-200 text-sm"><input name="notes" placeholder="Notes (optional)" class="rounded-lg border-slate-200 text-sm md:col-span-2 xl:col-span-5"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Create task</button></form></section>@endif

<form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-[1.5fr_1fr_1fr_1fr_auto]"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search tasks" class="rounded-lg border-slate-200 text-sm"><select name="property" class="rounded-lg border-slate-200 text-sm"><option value="">All properties</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected(($filters['property']??null)===$property->id)>{{ $property->name }}</option>@endforeach</select><select name="status" class="rounded-lg border-slate-200 text-sm"><option value="">All statuses</option>@foreach(['pending','assigned','in_progress','blocked','completed','cancelled'] as $value)<option value="{{ $value }}" @selected(($filters['status']??null)===$value)>{{ str($value)->replace('_',' ')->title() }}</option>@endforeach</select><select name="priority" class="rounded-lg border-slate-200 text-sm"><option value="">All priorities</option>@foreach(['low','normal','high','urgent'] as $value)<option value="{{ $value }}" @selected(($filters['priority']??null)===$value)>{{ str($value)->title() }}</option>@endforeach</select><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Apply</button></form>

<section class="grid gap-4 xl:grid-cols-2">
@forelse($tasks as $task)
<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div class="flex flex-wrap items-center gap-2"><span class="font-mono text-[10px] text-slate-400">{{ $task->reference }}</span><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{{ str($task->status->value)->replace('_',' ')->title() }}</span><span class="rounded-full {{ $task->priority->value==='urgent'?'bg-red-50 text-red-700':'bg-orange-50 text-orange-700' }} px-2 py-1 text-[10px] font-bold">{{ str($task->priority->value)->title() }}</span>@if($task->generation_source->value==='system')<span class="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">Automated</span>@endif</div>
    <h2 class="mt-2 text-lg font-extrabold">{{ $task->title }}</h2>
    <p class="mt-1 text-xs text-slate-500">{{ $task->property->name }} · {{ str($task->task_type->value)->replace('_',' ')->title() }} · Due {{ optional($task->due_at)->format('d M Y, H:i')??'Not set' }}</p>
    @if($task->booking)<a href="{{ route('owner.bookings.show',$task->booking) }}" class="mt-3 block rounded-xl bg-orange-50 p-3 text-xs text-orange-900"><strong>{{ $task->booking->reference }}</strong> · {{ $task->booking->guest->name }}<br>{{ $task->booking->arrival_date->format('d M') }} – {{ $task->booking->departure_date->format('d M Y') }}</a>@endif
    @if($task->assignedEmployee)<p class="mt-3 text-xs font-semibold text-slate-600">Assigned to {{ $task->assignedEmployee->businessMembership->user->name }}</p>@else<p class="mt-3 text-xs font-semibold text-amber-700">Unassigned — owner action required</p>@endif
    @if($canReassignTasks && !in_array($task->status->value,['completed','cancelled'],true))<form method="POST" action="{{ route('owner.operations.tasks.assign',$task) }}" class="mt-3 flex flex-col gap-2 sm:flex-row">@csrf @method('PATCH')<select name="assigned_employee_id" required class="min-w-0 flex-1 rounded-lg border-slate-200 text-xs"><option value="">Assign team member</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected($task->assigned_employee_id===$employee->id)>{{ $employee->businessMembership->user->name }} · {{ $employee->businessMembership->job_title ?: 'Operations' }}</option>@endforeach</select><button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">{{ $task->assigned_employee_id?'Reassign':'Assign' }}</button></form>@endif
    @if($canAssignTasks && !in_array($task->status->value,['completed','cancelled'],true))<form method="POST" action="{{ route('owner.operations.tasks.schedule',$task) }}" class="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]">@csrf @method('PATCH')<input type="datetime-local" name="due_at" required value="{{ $task->due_at?->format('Y-m-d\\TH:i') }}" class="rounded-lg border-slate-200 text-xs"><select name="priority" class="rounded-lg border-slate-200 text-xs">@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}" @selected($task->priority->value===$priority)>{{ str($priority)->title() }}</option>@endforeach</select><button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Update schedule</button></form>@endif
    @if($task->notes)<p class="mt-3 text-sm text-slate-600">{{ $task->notes }}</p>@endif
    @if($task->verification_notes)<p class="mt-3 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-800"><strong>Completion notes:</strong> {{ $task->verification_notes }}</p>@endif
    @if($task->attachments->isNotEmpty())<div class="mt-3"><p class="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Private evidence</p><div class="mt-2 flex flex-wrap gap-2">@foreach($task->attachments as $attachment)<a href="{{ route('task-attachments.show',[$task,$attachment]) }}" target="_blank" rel="noopener" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">{{ $attachment->original_name ?: 'View evidence' }}</a>@endforeach</div></div>@endif

    @if($canCompleteTasks && in_array($task->status->value,['pending','assigned'],true))
        <form method="POST" action="{{ route('owner.operations.tasks.transition',$task) }}" class="mt-4">@csrf @method('PATCH')<input type="hidden" name="action" value="start"><button class="rounded-lg bg-slate-950 px-4 py-2 text-xs font-bold text-white">Start task</button></form>
    @elseif($canInspect && $task->status->value==='in_progress' && $task->task_type->value==='inspection' && $task->booking_id)
        <form method="POST" enctype="multipart/form-data" action="{{ route('owner.operations.tasks.inspection',$task) }}" class="mt-4 space-y-3 rounded-xl border border-slate-200 p-4">@csrf<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold">Result<select name="result" required class="mt-1 w-full rounded-lg border-slate-200"><option value="passed">Pass — property ready</option><option value="failed">Fail — corrective work needed</option></select></label><label class="text-xs font-bold">If failed<select name="corrective_action" class="mt-1 w-full rounded-lg border-slate-200"><option value="cleaning">Repeat cleaning</option><option value="maintenance">Create maintenance issue</option></select></label></div><textarea name="findings" rows="2" placeholder="Inspection findings" class="w-full rounded-lg border-slate-200 text-sm"></textarea><label class="block text-xs font-bold">Inspection evidence<input type="file" name="evidence[]" multiple accept="image/*" class="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-xs"></label><button class="rounded-lg bg-emerald-600 px-4 py-2 text-xs font-bold text-white">Complete inspection</button></form>
    @elseif($canCompleteTasks && $task->status->value==='in_progress')
        <form method="POST" enctype="multipart/form-data" action="{{ route('owner.operations.tasks.transition',$task) }}" class="mt-4 rounded-xl border border-slate-200 p-4">@csrf @method('PATCH')<input type="hidden" name="action" value="complete">@if($task->checklistItems->isNotEmpty())<p class="mb-2 text-xs font-extrabold uppercase text-slate-400">Required checklist</p><div class="space-y-2">@foreach($task->checklistItems as $item)<label class="flex items-start gap-2 text-sm"><input type="checkbox" name="checklist_items[]" value="{{ $item->id }}" @checked($item->is_completed) class="mt-0.5 rounded border-slate-300 text-orange-600"><span>{{ $item->title }}</span></label>@endforeach</div>@endif<label class="mt-3 block text-xs font-bold text-slate-600">Before/after evidence<input type="file" name="evidence[]" multiple accept="image/*" class="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-xs"></label><textarea name="completion_notes" required rows="2" placeholder="Completion notes" class="mt-3 w-full rounded-lg border-slate-200 text-sm"></textarea><button class="mt-3 rounded-lg bg-emerald-600 px-4 py-2 text-xs font-bold text-white">Complete task</button></form>
    @endif
</article>
@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center xl:col-span-2"><h2 class="font-extrabold">No operational tasks</h2><p class="mt-2 text-sm text-slate-500">Create a task or adjust the active filters.</p></div>@endforelse
</section>{{ $tasks->links() }}
</main></div></div></body></html>
