@extends('layouts.admin', ['title' => 'Platform configuration', 'pageTitle' => 'Platform configuration'])

@section('content')
<div class="mx-auto max-w-5xl space-y-5">
    <section class="rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-8"><p class="text-xs font-black uppercase tracking-[.18em] text-orange-400">Platform owner settings</p><h2 class="mt-2 text-2xl font-black">Operational policy, in one auditable place.</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Only the platform owner can control provider environments, credentials, booking policy, installments and fees. Other administrators, business teams and guests cannot access this page. Changes are encrypted where sensitive and written to audit history.</p></section>
    <form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-5">@csrf @method('PATCH')
        @foreach($settings as $group => $items)
            <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4 sm:px-6"><h3 class="font-black">{{ str($group)->title() }}</h3>@if($group === 'payments')<p class="mt-1 text-xs font-semibold text-slate-500">These are platform-owned keys. Guest payments route through Verified Shortlet before owner settlement. Paystack verifies webhooks with its active secret API key; Flutterwave uses the separate secret hash configured in its dashboard.</p>@endif</div><div class="divide-y divide-slate-100">
                @foreach($items as $setting)
                    <div class="grid gap-4 px-5 py-5 sm:grid-cols-[1fr_16rem] sm:items-center sm:px-6"><div><label for="setting-{{ str($setting['key'])->slug() }}" class="text-sm font-black text-slate-900">{{ $setting['label'] }}</label><p class="mt-1 text-xs leading-5 text-slate-500">{{ $setting['description'] }}</p>@if($setting['updated_at'])<p class="mt-1 text-[11px] font-semibold text-slate-400">Last updated {{ $setting['updated_at']->diffForHumans() }} by {{ $setting['updated_by'] }}</p>@endif</div><div>
                        @php [$groupKey,$fieldKey]=explode('.',$setting['key'],2); $name="settings[{$groupKey}][{$fieldKey}]"; @endphp
                        @if($setting['key']==='payments.gateway_execution_mode')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="test" @selected($setting['value']==='test')>Test mode</option><option value="live" @selected($setting['value']==='live')>Live mode</option></select>
                        @elseif($setting['key']==='payments.active_provider')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="paystack" @selected($setting['value']==='paystack')>Paystack</option><option value="flutterwave" @selected($setting['value']==='flutterwave')>Flutterwave</option></select>
                        @elseif($setting['key']==='identity.environment')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="test" @selected($setting['value']==='test')>Test mode</option><option value="live" @selected($setting['value']==='live')>Live mode</option></select>
                        @elseif($setting['key']==='notifications.mail_provider')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="gmail" @selected($setting['value']==='gmail')>Gmail SMTP</option><option value="brevo" @selected($setting['value']==='brevo')>Brevo SMTP</option><option value="custom" @selected($setting['value']==='custom')>Custom SMTP</option></select>
                        @elseif($setting['key']==='notifications.mail_scheme')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="smtp" @selected(in_array($setting['value'], ['smtp','tls',null,''], true))>SMTP / STARTTLS (port 587)</option><option value="smtps" @selected(in_array($setting['value'], ['smtps','ssl'], true))>SMTPS / implicit TLS (port 465)</option></select>
                        @elseif($setting['key']==='storage.media_driver')<select id="setting-{{ str($setting['key'])->slug() }}" name="{{ $name }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200"><option value="local" @selected($setting['value']==='local')>Local public storage</option><option value="s3" @selected($setting['value']==='s3')>S3-compatible storage</option></select>
                        @elseif($setting['type']==='boolean')<input type="hidden" name="{{ $name }}" value="0"><label class="flex cursor-pointer items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold"><span>{{ $setting['value'] ? 'Enabled' : 'Disabled' }}</span><input id="setting-{{ str($setting['key'])->slug() }}" type="checkbox" name="{{ $name }}" value="1" @checked($setting['value']) class="rounded border-slate-300 text-orange-600 focus:ring-orange-500"></label>
                        @elseif($setting['type']==='integer')<input id="setting-{{ str($setting['key'])->slug() }}" type="number" name="{{ $name }}" value="{{ old("settings.{$groupKey}.{$fieldKey}",$setting['value']) }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200">
                        @elseif($setting['type']==='decimal')<input id="setting-{{ str($setting['key'])->slug() }}" type="number" min="0" step="0.01" name="{{ $name }}" value="{{ old("settings.{$groupKey}.{$fieldKey}",$setting['value']) }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200">
                        @elseif($setting['type']==='secret')<input id="setting-{{ str($setting['key'])->slug() }}" type="password" name="{{ $name }}" value="" autocomplete="new-password" placeholder="{{ filled($setting['value']) ? 'Saved — leave blank to keep' : 'Paste secret key' }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm placeholder:text-slate-400 focus:border-orange-400 focus:ring-orange-200">
                        @else<input id="setting-{{ str($setting['key'])->slug() }}" type="{{ $setting['key']==='support.contact_email' ? 'email' : 'text' }}" name="{{ $name }}" value="{{ old("settings.{$groupKey}.{$fieldKey}",$setting['value']) }}" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 shadow-sm focus:border-orange-400 focus:ring-orange-200">@endif
                    </div></div>
                @endforeach
            </div></section>
        @endforeach
        <section class="sticky bottom-4 rounded-2xl border border-orange-200 bg-orange-50 p-4 shadow-xl"><div class="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label class="text-sm font-black text-orange-950">Change reason<textarea name="reason" required minlength="10" maxlength="1000" rows="2" class="mt-2 block w-full rounded-xl border-orange-200 bg-white text-sm" placeholder="Explain why these platform settings are changing…">{{ old('reason') }}</textarea></label><button class="rounded-xl bg-orange-600 px-6 py-3 text-sm font-black text-white">Save configuration</button></div></section>
    </form>
    <details class="group rounded-2xl border border-slate-200 bg-white shadow-sm">
        <summary class="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 sm:px-6">
            <span><span class="block text-xs font-black uppercase tracking-[.16em] text-orange-600">Test mode reference</span><span class="mt-1 block text-lg font-black text-slate-950">Sandbox payment cards</span></span>
            <span class="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-xl font-black text-slate-700 transition group-open:rotate-45">+</span>
        </summary>
        <div class="border-t border-slate-100 px-5 py-5 sm:px-6">
            <div class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold leading-6 text-amber-950">These are checkout test cards—not API credentials. First save genuine provider test API keys above. Enter the card details only on the Paystack or Flutterwave hosted checkout page, and never use them in Live mode.</div>
            <div class="mt-4 grid gap-4 lg:grid-cols-2">
                <article class="rounded-2xl border border-slate-200 p-4">
                    <div class="flex items-center justify-between gap-3"><h4 class="font-black text-slate-950">Paystack</h4><a href="https://paystack.com/docs/payments/test-payments/" target="_blank" rel="noopener noreferrer" class="text-xs font-black text-orange-600 hover:underline">Official test data ↗</a></div>
                    <dl class="mt-4 grid grid-cols-[7.5rem_1fr] gap-x-3 gap-y-2 text-sm"><dt class="font-bold text-slate-500">Successful card</dt><dd class="font-mono font-bold text-slate-950">4084 0840 8408 4081</dd><dt class="font-bold text-slate-500">Expiry</dt><dd class="font-semibold">09/27</dd><dt class="font-bold text-slate-500">CVV</dt><dd class="font-semibold">408</dd><dt class="font-bold text-slate-500">Declined card</dt><dd class="font-mono font-bold text-slate-950">4084 0800 0000 5408</dd><dt class="font-bold text-slate-500">Expiry / CVV</dt><dd class="font-semibold">09/27 / 001</dd></dl>
                </article>
                <article class="rounded-2xl border border-slate-200 p-4">
                    <div class="flex items-center justify-between gap-3"><h4 class="font-black text-slate-950">Flutterwave</h4><a href="https://developer.flutterwave.com/docs/testing" target="_blank" rel="noopener noreferrer" class="text-xs font-black text-orange-600 hover:underline">Official test data ↗</a></div>
                    <dl class="mt-4 grid grid-cols-[7.5rem_1fr] gap-x-3 gap-y-2 text-sm"><dt class="font-bold text-slate-500">Successful card</dt><dd class="font-mono font-bold text-slate-950">5531 8866 5214 2950</dd><dt class="font-bold text-slate-500">Expiry / CVV</dt><dd class="font-semibold">09/32 / 564</dd><dt class="font-bold text-slate-500">PIN / OTP</dt><dd class="font-semibold">3310 / 12345</dd><dt class="font-bold text-slate-500">Failed card</dt><dd class="font-mono font-bold text-slate-950">5258 5859 2266 6506</dd><dt class="font-bold text-slate-500">Expiry / CVV</dt><dd class="font-semibold">09/31 / 883</dd><dt class="font-bold text-slate-500">PIN / OTP</dt><dd class="font-semibold">3310 / 12345</dd></dl>
                </article>
            </div>
        </div>
    </details>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
        <p class="text-xs font-black uppercase tracking-[.16em] text-orange-600">Email verification</p>
        <h3 class="mt-1 text-xl font-black">Send a connection test</h3>
        <p class="mt-2 text-sm text-slate-500">Save the SMTP credentials above first, then send a real delivery test to a mailbox you can inspect.</p>
        <form method="POST" action="{{ route('admin.settings.test-email') }}" class="mt-4 flex flex-col gap-3 sm:flex-row">@csrf
            <input type="email" name="recipient" required value="{{ auth()->user()->email }}" class="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold" aria-label="Test email recipient">
            <button class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white hover:bg-orange-600">Send test email</button>
        </form>
    </section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
        <p class="text-xs font-black uppercase tracking-[.16em] text-orange-600">Storage verification</p>
        <h3 class="mt-1 text-xl font-black">Test media storage</h3>
        <p class="mt-2 text-sm text-slate-500">Performs a small write, read and delete check using the currently saved media-storage configuration.</p>
        <form method="POST" action="{{ route('admin.settings.test-storage') }}" class="mt-4 space-y-3">@csrf
            <label class="flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold"><input type="checkbox" name="confirm" value="1" required class="mt-1 rounded border-slate-300 text-orange-600"><span>I confirm this storage connection check.</span></label>
            <button class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white hover:bg-orange-600">Run storage check</button>
        </form>
    </section>
</div>
@endsection
