@extends('layouts.app')
@section('title', 'Confirm and pay – Verified Shortlet')
@section('content')
<x-navbar />
@php
    $media=$property->media->firstWhere('is_primary',true)??$property->media->first(); $image=$media?->external_url?:($media?->storage_path?'/storage/'.ltrim($media->storage_path,'/'):'/image.png');
    $subtotal=(float)$quote->decimal($quote->subtotalMinor); $discount=(float)$quote->decimal($quote->discountMinor); $serviceFee=(float)$quote->decimal($quote->serviceFeeMinor); $tax=(float)$quote->decimal($quote->taxMinor); $total=(float)$quote->decimal($quote->totalMinor); $guestCount=$adultCount+$childCount;
    $balanceAmount = max(0, $total - (float) $depositAmount);
    $rating=$property->reviews->avg('rating'); $reviewCount=$property->reviews->count();
@endphp
<main class="min-h-screen bg-[#f3f3f2] py-7 sm:py-10">
    <div class="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-10">
        <header class="flex flex-col gap-5 border-b border-slate-200 pb-5 lg:flex-row lg:items-center lg:justify-between"><div><h1 class="text-3xl font-black">Confirm and pay</h1><p class="mt-2 text-sm text-slate-500">Verified Shortlet &gt; Explore stays &gt; {{ $property->marketplaceListing->public_title }} &gt; Checkout</p></div><div class="flex items-center gap-2 text-sm font-bold sm:gap-4"><span class="flex items-center gap-2"><i class="grid size-8 place-items-center rounded-full bg-emerald-600 text-white">✓</i>Stay</span><i class="h-px w-8 bg-slate-300 sm:w-20"></i><span class="flex items-center gap-2"><i class="grid size-8 place-items-center rounded-full bg-emerald-600 text-white">✓</i>Guest details</span><i class="h-px w-8 bg-slate-300 sm:w-20"></i><span class="flex items-center gap-2"><i class="grid size-8 place-items-center rounded-full bg-orange-600 text-white">3</i>Payment</span></div></header>

        @if($errors->any())<div class="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('marketplace.checkout.store',$property->marketplaceListing->slug) }}" class="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_440px] lg:items-start" x-data="{ provider: '{{ old('payment_provider', 'paystack') }}', option: '{{ old('payment_option', 'full') }}', customDeposit: '{{ old('deposit_amount', '') }}', total: {{ $total }}, minimumDeposit: {{ (float) $depositAmount }}, get depositDue() { const amount = Number(this.customDeposit || 0); if (this.option !== 'installment') return this.total; return amount > 0 ? amount : this.minimumDeposit; }, get balanceDue() { return Math.max(0, this.total - this.depositDue); }, money(value) { return '₦' + Number(value || 0).toLocaleString(); } }">@csrf
            <input type="hidden" name="arrival_date" value="{{ $arrival->toDateString() }}"><input type="hidden" name="departure_date" value="{{ $departure->toDateString() }}"><input type="hidden" name="adult_count" value="{{ $adultCount }}"><input type="hidden" name="child_count" value="{{ $childCount }}"><input type="hidden" name="quoted_total" value="{{ $total }}"><input type="hidden" name="idempotency_key" value="{{ (string)Str::uuid() }}">
            <div class="space-y-4">
                <section class="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-6"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-600 text-xl text-white">✓</span><div><h2 class="text-lg font-black">Your stay</h2><p class="mt-1 text-sm text-slate-500">{{ $arrival->format('D, d M') }} – {{ $departure->format('D, d M Y') }} · {{ $quote->nights }} {{ Str::plural('night',$quote->nights) }} · {{ $guestCount }} {{ Str::plural('guest',$guestCount) }}</p></div><a href="{{ route('marketplace.show',$property->marketplaceListing->slug) }}" class="ml-auto font-bold text-orange-600">Edit</a></section>
                <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center gap-4"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-600 text-xl text-white">✓</span><div><h2 class="text-lg font-black">Guest details</h2><p class="mt-1 text-sm text-slate-500">{{ auth()->user()->name }} · {{ auth()->user()->email }}</p></div></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><input name="guest_phone" required maxlength="32" value="{{ old('guest_phone',auth()->user()->phone_number) }}" placeholder="Phone number" class="rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-orange-500 focus:ring-orange-500"><input name="special_requests" maxlength="1000" value="{{ old('special_requests') }}" placeholder="Special requests (optional)" class="rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-orange-500 focus:ring-orange-500"></div></section>
                @unless($identityVerified)
                    <section class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">
                        <h2 class="font-black">NIN verification required before payment</h2>
                        <p class="mt-2 leading-6">For guest safety and fraud control, complete NIN verification before paying for this stay.</p>
                        <a href="{{ route('guest.settings.edit') }}#profile" class="mt-3 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white">Verify now</a>
                    </section>
                @endunless
                <section class="rounded-2xl border border-slate-200 bg-white p-6 sm:p-7">
                    <div class="flex gap-4"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-orange-600 font-black text-white">3</span><div><h2 class="text-xl font-black">Payment method</h2><p class="mt-1 text-sm text-slate-500">Choose the gateway and whether to pay in full or reserve with a deposit.</p></div></div>
                    @if($installmentsEnabled)
                        <div class="mt-5 grid gap-3 sm:grid-cols-2">
                            <label class="cursor-pointer rounded-2xl border p-4 transition" :class="option === 'full' ? 'border-orange-500 bg-orange-50 ring-2 ring-orange-100' : 'border-slate-200 bg-white'"><input type="radio" name="payment_option" value="full" x-model="option" class="sr-only"><span class="block text-sm font-black">Pay in full</span><span class="mt-1 block text-xs leading-5 text-slate-500">Pay ₦{{ number_format($total) }} now and complete the booking.</span></label>
                            <label class="cursor-pointer rounded-2xl border p-4 transition" :class="option === 'installment' ? 'border-orange-500 bg-orange-50 ring-2 ring-orange-100' : 'border-slate-200 bg-white'"><input type="radio" name="payment_option" value="installment" x-model="option" class="sr-only"><span class="block text-sm font-black">{{ $depositPercentage }}% minimum deposit</span><span class="mt-1 block text-xs leading-5 text-slate-500">Pay at least ₦{{ number_format($depositAmount) }} now; the balance is due {{ $balanceDueHours }} hours before check-in.</span></label>
                        </div>
                        <div x-show="option === 'installment'" x-cloak class="mt-4 rounded-2xl border border-orange-100 bg-orange-50/60 p-4">
                            <label class="block text-xs font-black uppercase tracking-wide text-orange-900">Optional custom deposit amount
                                <input type="number" min="{{ $depositAmount }}" max="{{ $total }}" step="1000" name="deposit_amount" x-model="customDeposit" class="mt-2 w-full rounded-xl border border-orange-200 bg-white px-4 py-3 text-sm font-bold text-slate-900 focus:border-orange-500 focus:ring-orange-500" placeholder="Minimum ₦{{ number_format($depositAmount) }}">
                            </label>
                            <p class="mt-2 text-xs leading-5 text-orange-900">You can pay more than the minimum now. The system will not accept less than ₦{{ number_format($depositAmount) }}.</p>
                        </div>
                    @else
                        <input type="hidden" name="payment_option" value="full">
                    @endif
                    <div class="mt-5 grid gap-4 sm:grid-cols-2">
                        <label class="flex cursor-pointer items-center gap-3 rounded-xl border p-5 font-black transition" :class="provider === 'paystack' ? 'border-orange-600 bg-orange-50 ring-2 ring-orange-100' : 'border-slate-300 bg-white'"><input type="radio" name="payment_provider" value="paystack" x-model="provider" class="text-orange-600 focus:ring-orange-500">Paystack</label>
                        <label class="flex cursor-pointer items-center gap-3 rounded-xl border p-5 font-black transition" :class="provider === 'flutterwave' ? 'border-orange-600 bg-orange-50 ring-2 ring-orange-100' : 'border-slate-300 bg-white'"><input type="radio" name="payment_provider" value="flutterwave" x-model="provider" class="text-orange-600 focus:ring-orange-500">Flutterwave</label>
                    </div>
                    <div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><strong class="text-slate-950" x-text="option === 'installment' ? 'Deposit due now' : 'Amount due now'"></strong><span class="ml-2 font-black text-orange-600" x-text="money(option === 'installment' ? depositDue : total)"></span><p class="mt-1 text-xs" x-text="option === 'installment' ? 'Balance after this payment: '+money(balanceDue)+'. Full payment must be completed before check-in.' : 'Full payment must be completed before the check-in date.'"></p></div>
                    <label class="mt-8 flex items-start gap-3 border-y border-slate-200 py-5 text-sm"><input required type="checkbox" class="mt-0.5 rounded border-slate-300 text-orange-600 focus:ring-orange-500"><span><strong class="font-medium">I agree to the house rules, cancellation policy and Terms &amp; Conditions.</strong><small class="mt-1 block text-slate-500">Free cancellation more than {{ $freeCancellationHours }} hours before check-in. Eligible part-payment refunds are subject to the configured cancellation penalty.</small></span></label><p class="mt-5 text-sm text-slate-500">🔒 &nbsp; Payments are encrypted. Hosts never see your card details.</p><button @disabled(! $identityVerified) class="mt-7 w-full rounded-xl bg-orange-600 py-4 text-lg font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">🔒 &nbsp; <span x-text="option === 'installment' ? 'Pay deposit' : 'Pay now'"></span></button>
                </section>
            </div>
            <aside class="rounded-2xl border border-slate-200 bg-white p-5 lg:sticky lg:top-24"><div class="relative h-48 overflow-hidden rounded-xl"><img src="{{ $image }}" onerror="this.src='/image.png'" class="h-full w-full object-cover" alt="">@if($property->superhost_badge_enabled)<span class="absolute left-4 top-4 rounded-full bg-white px-4 py-2 text-xs font-extrabold text-orange-600">★ Super host</span>@endif</div><h2 class="mt-5 text-xl font-black">{{ $property->marketplaceListing->public_title }}</h2><p class="mt-1 text-sm text-slate-500">⌖ {{ data_get($property->address,'city') }}, {{ data_get($property->address,'state') }} · {{ str($property->property_type->value ?? $property->property_type)->replace('_',' ')->title() }}</p>@if($rating)<p class="mt-2 text-sm"><span class="text-orange-600">★</span> {{ number_format($rating,1) }} ({{ $reviewCount }} reviews)</p>@endif <div class="mt-5 border-t border-slate-200 pt-5"><h3 class="font-black">Price details</h3><div class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><span>₦{{ number_format((float)$property->default_nightly_price) }} × {{ $quote->nights }} nights</span><strong>₦{{ number_format($subtotal) }}</strong></div>@if($discount>0)<div class="flex justify-between text-emerald-700"><span>Stay discount</span><strong>−₦{{ number_format($discount) }}</strong></div>@endif @if($serviceFee>0)<div class="flex justify-between"><span>Platform fee</span><strong>₦{{ number_format($serviceFee) }}</strong></div>@endif @if($tax>0)<div class="flex justify-between"><span>Tax</span><strong>₦{{ number_format($tax) }}</strong></div>@endif <div class="flex justify-between border-t border-slate-200 pt-4 text-lg"><strong>Total (NGN)</strong><strong>₦{{ number_format($total) }}</strong></div>@if($installmentsEnabled)<div class="rounded-xl bg-orange-50 p-3 text-xs text-orange-800"><strong>Installment option:</strong> minimum ₦{{ number_format($depositAmount) }} now, balance before check-in.</div>@endif</div></div><div class="mt-6 rounded-xl bg-slate-100 p-5"><h3 class="font-black text-orange-600">♢ &nbsp; Booked with confidence</h3><p class="mt-3 text-sm leading-6 text-slate-500">Every stay is ID-checked and inspected before it appears in search results.</p></div></aside>
        </form>
    </div>
</main>
@endsection
