@extends('layouts.admin', ['title' => 'Review moderation', 'pageTitle' => 'Review moderation'])

@section('content')
<div class="mx-auto max-w-7xl space-y-5">
    <div><p class="text-sm font-semibold text-slate-500">Preserve authentic guest voices while keeping public content safe.</p><p class="mt-1 text-xs text-slate-400">{{ number_format($reviews->total()) }} verified-stay reviews</p></div>
    <form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_12rem_10rem_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Review, guest or property" class="rounded-xl border-slate-200 text-sm focus:border-orange-400 focus:ring-orange-200"><select name="moderation_status" class="rounded-xl border-slate-200 text-sm"><option value="">All moderation</option>@foreach(['pending','approved','hidden','rejected'] as $status)<option value="{{ $status }}" @selected(($filters['moderation_status']??'')===$status)>{{ str($status)->title() }}</option>@endforeach</select><select name="rating" class="rounded-xl border-slate-200 text-sm"><option value="">Any rating</option>@foreach(range(5,1) as $rating)<option value="{{ $rating }}" @selected((string)($filters['rating']??'')===(string)$rating)>{{ $rating }} stars</option>@endforeach</select><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Apply filters</button></form>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="hidden grid-cols-[1.25fr_.9fr_.55fr_.6fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[11px] font-black uppercase tracking-wider text-slate-500 md:grid"><span>Review</span><span>Property</span><span>Rating</span><span>Moderation</span><span></span></div><div class="divide-y divide-slate-100">@forelse($reviews as $review)<article class="grid gap-4 px-5 py-4 hover:bg-slate-50 md:grid-cols-[1.25fr_.9fr_.55fr_.6fr_auto] md:items-center"><div><p class="line-clamp-1 text-sm font-black">{{ $review->title ?: Str::limit($review->content,55) }}</p><p class="mt-1 line-clamp-1 text-xs text-slate-500">{{ $review->guest->name }} · {{ $review->content }}</p></div><div><p class="text-sm font-bold">{{ $review->property->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $review->property->business->name }}</p></div><p class="font-black text-orange-600">★ {{ $review->rating }}</p><div class="flex flex-wrap gap-1"><span class="rounded-full px-2.5 py-1 text-[11px] font-black {{ $review->moderation_status==='approved'?'bg-emerald-100 text-emerald-800':($review->moderation_status==='hidden'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800') }}">{{ str($review->moderation_status)->title() }}</span>@if($review->response)<span class="rounded-full bg-sky-50 px-2 py-1 text-[10px] font-bold text-sky-700">Response</span>@endif</div><a href="{{ route('admin.reviews.show',$review) }}" class="rounded-xl bg-orange-600 px-4 py-2 text-center text-sm font-black text-white">Open case</a></article>@empty<div class="p-12 text-center text-sm font-bold text-slate-500">No reviews match these filters.</div>@endforelse</div></section>{{ $reviews->links() }}
</div>
@endsection
