@extends('layouts.admin', ['title' => 'Review case', 'pageTitle' => 'Review case'])

@section('content')
@php $canModerate=app(\App\Services\PlatformPermissionService::class)->allows(auth()->user(),'platform.review.moderate'); @endphp
<div class="mx-auto max-w-5xl space-y-5" x-data="{ moderationAction: null, actionUrl: '' }">
    <a href="{{ route('admin.reviews.index') }}" class="inline-flex text-sm font-black text-orange-600">← Review moderation</a>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex flex-col justify-between gap-5 sm:flex-row"><div><p class="text-xs font-black uppercase tracking-[.18em] text-emerald-700">✓ Verified stay</p><h2 class="mt-2 text-2xl font-black">{{ $review->property->name }}</h2><p class="mt-2 text-sm text-slate-500">{{ $review->guest->name }} · Booking {{ $review->booking->reference }}</p></div><div class="text-right"><p class="text-2xl font-black text-orange-600">★ {{ $review->rating }}/5</p><span class="mt-2 inline-flex rounded-full px-3 py-1 text-xs font-black {{ $review->moderation_status==='approved'?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800' }}">{{ str($review->moderation_status)->title() }}</span></div></div><div class="mt-7 rounded-2xl bg-slate-50 p-5"><h3 class="font-black">{{ $review->title ?: 'Guest review' }}</h3><p class="mt-3 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $review->content }}</p><p class="mt-3 text-xs font-semibold text-slate-400">Published {{ $review->published_at?->format('d M Y, H:i') }}</p></div>@if($canModerate)<div class="mt-4 flex justify-end">@if($review->moderation_status==='hidden')<button @click="moderationAction='Restore review'; actionUrl='{{ route('admin.reviews.restore',$review) }}'" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Restore review</button>@else<button @click="moderationAction='Hide review'; actionUrl='{{ route('admin.reviews.hide',$review) }}'" class="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-black text-white">Hide review</button>@endif</div>@endif</section>
    @if($review->response)<section class="rounded-3xl border border-orange-200 bg-orange-50 p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><p class="text-xs font-black uppercase tracking-widest text-orange-700">Owner response</p><p class="mt-3 text-sm leading-7 text-slate-700">{{ $review->response->content }}</p><p class="mt-2 text-xs text-slate-500">{{ str($review->response->moderation_status)->title() }} · {{ $review->response->published_at?->format('d M Y, H:i') }}</p></div>@if($canModerate)<div class="shrink-0">@if($review->response->moderation_status==='hidden')<button @click="moderationAction='Restore owner response'; actionUrl='{{ route('admin.review-responses.restore',$review->response) }}'" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Restore response</button>@else<button @click="moderationAction='Hide owner response'; actionUrl='{{ route('admin.review-responses.hide',$review->response) }}'" class="rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-black text-red-700">Hide response</button>@endif</div>@endif</div></section>@endif
    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Moderation history</h3></div><div class="divide-y divide-slate-100">@forelse($audits as $event)<div class="grid gap-1 px-5 py-4 sm:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold">{{ $event->description }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name }} · {{ data_get($event->metadata,'reason') }}</p></div><time class="text-xs text-slate-400">{{ $event->occurred_at?->format('d M Y, H:i') }}</time></div>@empty<div class="p-8 text-center text-sm text-slate-500">No moderation actions recorded.</div>@endforelse</div></section>
    @if($canModerate)<div x-cloak x-show="moderationAction" class="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm"><div class="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" @click.outside="moderationAction=null"><div class="flex justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-orange-600">Moderation decision</p><h3 class="mt-2 text-xl font-black" x-text="moderationAction"></h3></div><button @click="moderationAction=null" class="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div><p class="mt-3 text-sm text-slate-600">The original content and publication timestamp remain preserved.</p><form method="POST" :action="actionUrl" class="mt-5">@csrf<textarea name="reason" required minlength="10" maxlength="1000" rows="4" class="block w-full rounded-xl border-slate-200 text-sm focus:border-orange-400 focus:ring-orange-200" placeholder="State the policy or evidence-based reason…"></textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="moderationAction=null" class="rounded-xl px-4 py-2.5 text-sm font-black text-slate-600">Cancel</button><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Confirm moderation</button></div></form></div></div>@endif
</div>
@endsection
