<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $booking->reference }} – Receipt</title>@vite(['resources/css/app.css'])<style>@media print{.no-print{display:none!important}body{background:#fff!important}.receipt{box-shadow:none!important;border:0!important}}</style></head>
@php
    $symbol=$booking->currency==='NGN'?'₦':$booking->currency.' ';
    $paid=(float)$booking->payments->filter(fn($p)=>$p->status->value==='completed' && $p->purpose->value!=='refund')->sum('amount');
    $refunded=(float)$booking->payments->filter(fn($p)=>$p->status->value==='completed' && $p->purpose->value==='refund')->sum('amount');
    $outstanding=max(0,(float)$booking->total_amount-$paid);
@endphp
<body class="bg-slate-100 p-4 font-sans text-slate-950 sm:p-10"><main class="receipt mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div class="flex flex-wrap items-start justify-between gap-4 border-b pb-6"><div><p class="text-xs font-extrabold uppercase tracking-[.18em] text-orange-600">Verified Shortlet</p><h1 class="mt-2 text-3xl font-extrabold">Booking receipt</h1><p class="mt-2 font-mono text-sm text-slate-500">{{ $booking->reference }}</p></div><button onclick="window.print()" class="no-print rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Print / save PDF</button></div><div class="grid gap-6 border-b py-6 sm:grid-cols-2"><div><p class="text-xs font-bold uppercase text-slate-400">Guest</p><p class="mt-2 font-extrabold">{{ $booking->guest->name }}</p><p class="text-sm text-slate-500">{{ $booking->guest->email }}</p></div><div><p class="text-xs font-bold uppercase text-slate-400">Property</p><p class="mt-2 font-extrabold">{{ $booking->property->marketplaceListing?->public_title ?: $booking->property->name }}</p><p class="text-sm text-slate-500">{{ $booking->arrival_date->format('d M Y') }} – {{ $booking->departure_date->format('d M Y') }}</p></div></div><div class="py-6"><h2 class="font-extrabold">Amount summary</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt>Stay subtotal</dt><dd class="font-bold">{{ $symbol }}{{ number_format((float)$booking->subtotal_amount) }}</dd></div>@if((float)$booking->discount_amount > 0)<div class="flex justify-between text-emerald-700"><dt>Manual discount</dt><dd class="font-bold">−{{ $symbol }}{{ number_format((float)$booking->discount_amount) }}</dd></div>@endif<div class="flex justify-between border-t pt-3 text-base"><dt class="font-extrabold">Total</dt><dd class="font-extrabold">{{ $symbol }}{{ number_format((float)$booking->total_amount) }}</dd></div><div class="flex justify-between text-emerald-700"><dt>Paid</dt><dd class="font-extrabold">{{ $symbol }}{{ number_format($paid) }}</dd></div>@if($refunded>0)<div class="flex justify-between text-amber-700"><dt>Refunded</dt><dd class="font-extrabold">{{ $symbol }}{{ number_format($refunded) }}</dd></div>@endif<div class="flex justify-between text-orange-700"><dt>Outstanding</dt><dd class="font-extrabold">{{ $symbol }}{{ number_format($outstanding) }}</dd></div></dl></div><p class="border-t pt-5 text-xs leading-5 text-slate-400">Generated {{ now()->format('d M Y, H:i') }}. Payments in this development MVP are simulated or manually recorded and clearly identified in the booking record.</p><a href="{{ route('guest.bookings.show',$booking) }}" class="no-print mt-6 inline-block text-sm font-bold text-orange-600">← Back to booking</a></main></body></html>
