@extends('layouts.app')
@section('title', 'Booking confirmed – Verified Shortlet')
@section('content')
<x-navbar />
@php
    $property=$booking->property; $media=$property->media->firstWhere('is_primary',true)??$property->media->first(); $image=$media?->external_url?:($media?->storage_path?'/storage/'.ltrim($media->storage_path,'/'):'/image.png'); $payment=$booking->payments->sortByDesc('created_at')->first(); $nights=$booking->arrival_date->diffInDays($booking->departure_date); $firstName=Str::of(auth()->user()->name)->squish()->explode(' ')->first(); $host=Str::of($booking->business?->primary_contact_name ?: 'Verified host')->squish()->explode(' ')->first();
@endphp
<main class="min-h-screen bg-[#f3f3f2] py-8 sm:py-10"><div class="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-10">
    <section class="rounded-2xl bg-[#191919] p-6 text-white sm:p-8"><div class="flex flex-col gap-6 lg:flex-row lg:items-center"><span class="grid size-16 shrink-0 place-items-center rounded-full bg-emerald-600 text-3xl">✓</span><div class="max-w-2xl"><h1 class="text-2xl font-black text-orange-500 sm:text-3xl">Booking confirmed, {{ $firstName }}!</h1><p class="mt-3 text-sm leading-6 text-slate-300 sm:text-base">Your stay at {{ $property->marketplaceListing?->public_title ?: $property->name }} is booked. A confirmation and receipt are available in your account.</p><span class="mt-4 inline-flex rounded-full bg-white/10 px-4 py-2 text-xs font-bold">Booking ref {{ $booking->reference }}</span></div><div class="flex flex-wrap gap-3 lg:ml-auto"><a href="{{ route('guest.bookings.messages.show',$booking) }}" class="rounded-xl bg-white/10 px-5 py-3 text-sm font-bold">▢ Message host</a><a href="{{ route('guest.bookings.show',$booking) }}" class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold">▣ View booking</a></div></div></section>
    <div class="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_440px]"><div class="space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div class="grid gap-5 sm:grid-cols-[280px_1fr]"><img src="{{ $image }}" onerror="this.src='/image.png'" class="h-48 w-full rounded-xl object-cover" alt=""><div><h2 class="text-2xl font-black">{{ $property->marketplaceListing?->public_title ?: $property->name }}</h2><p class="mt-2 text-sm text-slate-500">⌖ {{ data_get($property->address,'city') }}, {{ data_get($property->address,'state') }} · Serviced apartment</p><div class="mt-5 flex gap-3"><span class="rounded-full bg-emerald-700 px-4 py-2 text-xs font-bold text-white">Confirmed</span><span class="rounded-full bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-700">♢ Verified</span></div><p class="mt-5 text-sm text-slate-500">{{ $property->bedrooms }} {{ Str::plural('bedroom',$property->bedrooms) }} · {{ $property->beds }} {{ Str::plural('bed',$property->beds) }} · {{ $property->capacity }} guests</p></div></div><div class="mt-6 grid grid-cols-2 gap-5 border-t border-slate-100 pt-5 sm:grid-cols-4">@foreach([['▣','CHECK-IN',$booking->arrival_date->format('D, d M')],['▣','CHECK-OUT',$booking->departure_date->format('D, d M')],['♙','GUESTS',$booking->number_of_guests.' guests'],['✓','BOOKING REF',$booking->reference]] as [$icon,$label,$value])<div><p class="text-xs font-bold text-slate-500"><span class="text-orange-600">{{ $icon }}</span> {{ $label }}</p><strong class="mt-2 block">{{ $value }}</strong></div>@endforeach</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-6 sm:p-7"><h2 class="text-xl font-black">What happens next</h2><div class="relative mt-6 space-y-8 before:absolute before:bottom-5 before:left-[17px] before:top-5 before:w-px before:bg-slate-300">@foreach([['✓','Booking confirmed','Just now · Payment received and host notified','bg-emerald-600 text-white'],['▢','Door code and directions','Your host will share arrival details before check-in','border-2 border-orange-600 bg-white text-orange-600'],['⌂','Check-in',$booking->arrival_date->format('D, d M').' from '.substr($property->marketplaceListing?->check_in_time ?: '14:00',0,5),'border-2 border-orange-600 bg-white text-orange-600'],['☆','Check-out and review',$booking->departure_date->format('D, d M').' · leave a review after your stay','border-2 border-orange-600 bg-white text-orange-600']] as [$icon,$title,$copy,$tone])<div class="relative flex gap-4"><span class="z-10 grid size-9 shrink-0 place-items-center rounded-full {{ $tone }}">{{ $icon }}</span><div><h3 class="font-black">{{ $title }}</h3><p class="mt-1 text-sm text-slate-500">{{ $copy }}</p></div></div>@endforeach</div></section>
    </div><aside class="space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Payment receipt</h2><span class="rounded-full bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-700">Paid</span></div><div class="mt-6 space-y-4 text-sm"><div class="flex justify-between"><span>₦{{ number_format((float)$property->default_nightly_price) }} × {{ $nights }} nights</span><strong>₦{{ number_format((float)$booking->subtotal_amount) }}</strong></div>@if((float)$booking->discount_amount>0)<div class="flex justify-between text-emerald-700"><span>Longer-stay discount</span><strong>−₦{{ number_format((float)$booking->discount_amount) }}</strong></div>@endif<div class="flex justify-between"><span>Taxes &amp; fees</span><span class="text-slate-500">Included</span></div><div class="flex justify-between border-y border-slate-200 py-5 text-lg"><strong>Total paid</strong><strong>₦{{ number_format((float)$booking->total_amount) }}</strong></div>@if($payment)<div class="flex justify-between"><span class="text-slate-500">Paid with</span><strong>{{ str($payment->provider->value ?? $payment->provider)->title() }}</strong></div><div class="flex justify-between"><span class="text-slate-500">Date</span><strong>{{ ($payment->transaction_at??$payment->created_at)->format('d M Y, g:i A') }}</strong></div><div class="flex justify-between gap-4"><span class="text-slate-500">Transaction ID</span><strong class="truncate">{{ $payment->provider_reference ?: $payment->reference }}</strong></div>@endif</div><a href="{{ route('guest.bookings.receipt',$booking) }}" class="mt-7 block rounded-xl border border-slate-300 px-5 py-3.5 text-center text-sm font-bold">↓ &nbsp; Download receipt</a></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center gap-4"><span class="grid size-12 place-items-center rounded-full bg-orange-100 font-black text-orange-700">{{ Str::of($host)->substr(0,2)->upper() }}</span><div><h2 class="font-black">Your host · {{ $host }}</h2><p class="mt-1 text-sm text-slate-500">♢ Verified host</p></div></div><a href="{{ route('guest.bookings.messages.show',$booking) }}" class="mt-5 block rounded-xl border border-slate-300 py-3 text-center text-sm font-bold">▢ &nbsp; Message host</a></section>
        <section class="rounded-2xl bg-[#191919] p-6 text-white"><p class="text-xs font-black uppercase tracking-wide text-orange-500">✧ &nbsp; AI Stay Concierge</p><p class="mt-4 text-sm leading-6 text-slate-300">Planning your stay? Ask for nearby restaurants, transport and local tips.</p><button type="button" disabled class="mt-5 rounded-xl bg-orange-600 px-7 py-3 text-sm font-bold opacity-80">Plan my stay</button></section>
    </aside></div>
</div></main>
@endsection
