@extends('layouts.app')
@section('content')
<x-navbar />
@php
    $property = $booking->property;
    $media = $property->media->firstWhere('is_primary', true) ?? $property->media->firstWhere('media_type', \App\Enums\PropertyMediaType::Image);
    $image = $media?->external_url ?: ($media?->storage_path ? '/storage/'.ltrim($media->storage_path, '/') : '/image.png');
    $status = $booking->status->value;
    $statusClass = match($status) {'confirmed', 'checked_in' => 'bg-emerald-100 text-emerald-800', 'cancelled' => 'bg-red-100 text-red-700', 'awaiting_payment' => 'bg-amber-100 text-amber-800', default => 'bg-slate-100 text-slate-700'};
    $nights = $booking->arrival_date->diffInDays($booking->departure_date);
    $payment = $booking->payments->sortByDesc('created_at')->first();
    $paid = (float)$booking->payments->filter(fn($p)=>$p->status->value==='completed' && $p->purpose->value!=='refund')->sum('amount');
    $refunded = (float)$booking->payments->filter(fn($p)=>$p->status->value==='completed' && $p->purpose->value==='refund')->sum('amount');
    $outstanding = max(0,(float)$booking->total_amount-$paid);
    $timezone = $booking->business?->timezone ?: 'Africa/Lagos';
    $checkInTime = $property->marketplaceListing?->check_in_time ?: '14:00';
    $checkInAt = \Carbon\CarbonImmutable::parse($booking->arrival_date->toDateString().' '.$checkInTime, $timezone);
    $isRefundable = now($timezone)->lt($checkInAt->copy()->subHours(48));
    $review = $booking->reviews->first();
    $reviewInvitation = $booking->reviewInvitations->first();
    $reviewInvitationExpired = $reviewInvitation?->expires_at?->isPast() ?? false;
    $hostName = $booking->business?->primary_contact_name ?: $booking->business?->name ?: 'Verified Shortlet host';
    $hostInitials = collect(preg_split('/\s+/', trim($hostName)))->filter()->take(2)->map(fn ($part) => mb_strtoupper(mb_substr($part, 0, 1)))->implode('');
@endphp
<main class="min-h-screen bg-[#f3f3f2] px-4 py-8 sm:px-6 sm:py-10" x-data="{ cancelOpen:false, cancelling:false }">
<div class="mx-auto max-w-[1380px]">
    <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
        <div><a href="{{ route('guest.bookings.index') }}" class="text-sm font-semibold text-slate-500 hover:text-orange-600">Bookings / {{ $booking->reference }}</a><h1 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Booking details</h1></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('guest.bookings.messages.show', $booking) }}" class="inline-flex items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-800 hover:border-orange-300">Message host</a><a href="{{ route('guest.bookings.receipt',$booking) }}" class="inline-flex items-center justify-center rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-700">Download receipt</a></div>
    </div>
    @if(session('status'))<div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-bold">Please review the highlighted information.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="mt-7 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_370px]">
            <div class="space-y-7">
                <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="grid sm:grid-cols-[210px_1fr]"><img src="{{ $image }}" onerror="this.src='/image.png'" alt="{{ $property->name }}" class="h-48 w-full object-cover sm:h-full"><div class="p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.14em] text-slate-400">{{ $booking->reference }}</p><h2 class="mt-2 text-xl font-extrabold text-slate-950">{{ $property->marketplaceListing?->public_title ?: $property->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ data_get($property->address, 'city') }}, {{ data_get($property->address, 'state') }}</p></div><span class="rounded-full px-3 py-1.5 text-xs font-extrabold {{ $statusClass }}">{{ str($status)->replace('_', ' ')->title() }}</span></div><div class="mt-5 flex flex-wrap gap-2"><span class="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">✓ Verified property</span><span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{{ $property->bedrooms }} bedrooms</span><span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{{ $property->beds }} beds</span></div></div></div></section>
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-extrabold text-slate-950">Stay details</h2><div class="mt-5 grid grid-cols-2 gap-x-4 gap-y-6 sm:grid-cols-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Check in</p><strong class="mt-1 block text-sm">{{ $booking->arrival_date->format('d M Y') }}</strong></div><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Check out</p><strong class="mt-1 block text-sm">{{ $booking->departure_date->format('d M Y') }}</strong></div><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Guests</p><strong class="mt-1 block text-sm">{{ $booking->number_of_guests }} guests</strong><span class="text-[10px] text-slate-400">{{ $booking->adult_count }} adults · {{ $booking->child_count }} children</span></div><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Duration</p><strong class="mt-1 block text-sm">{{ $nights }} {{ Str::plural('night', $nights) }}</strong></div></div></section>
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-5 sm:flex-row sm:items-center"><div class="grid size-14 shrink-0 place-items-center rounded-full bg-orange-100 font-extrabold text-orange-700">{{ $hostInitials ?: 'VS' }}</div><div class="min-w-0 flex-1"><p class="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Your host</p><h2 class="mt-1 text-lg font-extrabold text-slate-950">Hosted by {{ Str::before($hostName, ' ') }}</h2><p class="mt-1 text-sm text-slate-500">Property team · Usually responds within a few hours</p></div><a href="{{ route('guest.bookings.messages.show', $booking) }}" class="rounded-xl bg-orange-600 px-4 py-2.5 text-center text-sm font-bold text-white">Message host</a></div><div class="mt-5 border-t border-slate-100 pt-5"><p class="text-sm font-bold text-slate-900">About this stay</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ $property->marketplaceListing?->public_description ?: $property->description ?: 'A verified property managed through Verified Shortlet.' }}</p></div></section>
                <section class="rounded-2xl bg-slate-950 p-5 text-white shadow-sm sm:p-6"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-orange-400">AI stay insight</p><h2 class="mt-2 text-lg font-extrabold">Everything for this booking, in one place</h2><p class="mt-2 text-sm leading-6 text-slate-300">Use Messages for help from the property team, and keep this page for payment, stay status, support requests and your verified review.</p></section>
                @if($booking->special_requests)<section class="rounded-2xl border border-slate-200 p-4"><h2 class="text-sm font-extrabold">Special requests</h2><p class="mt-2 text-sm text-slate-600">{{ $booking->special_requests }}</p></section>@endif
                @if($status==='checked_in')<section class="rounded-2xl border border-orange-200 bg-orange-50/40 p-5"><h2 class="text-lg font-extrabold">Need help during your stay?</h2><p class="mt-1 text-sm text-slate-600">Send a request directly to the property team. Urgent cleaning and maintenance requests create operational work automatically.</p><form method="POST" action="{{ route('guest.bookings.service-requests.store',$booking) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<label class="text-xs font-bold">Category<select name="request_type" required class="mt-1 w-full rounded-xl border-orange-200 bg-white"><option value="maintenance">Maintenance</option><option value="cleaning">Cleaning</option><option value="amenity">Amenity</option><option value="access">Access / keys</option><option value="noise">Noise</option><option value="other">Other</option></select></label><label class="text-xs font-bold">Urgency<select name="priority" required class="mt-1 w-full rounded-xl border-orange-200 bg-white"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><label class="text-xs font-bold sm:col-span-2">What do you need?<textarea name="description" required minlength="10" maxlength="2000" rows="3" class="mt-1 w-full rounded-xl border-orange-200 bg-white" placeholder="Describe the issue and where it is in the property"></textarea></label><button class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white sm:col-span-2">Send request</button></form></section>@endif
                @if($booking->serviceRequests->isNotEmpty())<section><h2 class="text-lg font-extrabold">Stay support</h2><div class="mt-3 space-y-3">@foreach($booking->serviceRequests->sortByDesc('requested_at') as $request)<article class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><div><p class="text-sm font-bold">{{ str($request->request_type)->title() }} request</p><p class="mt-1 text-xs text-slate-400">{{ $request->requested_at->format('d M Y, H:i') }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase">{{ $request->status }}</span></div><p class="mt-3 text-sm text-slate-600">{{ $request->description }}</p>@if($request->resolution)<div class="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800"><strong>Resolution:</strong> {{ $request->resolution }}</div>@endif</article>@endforeach</div></section>@endif
                @if($review)
                    <section class="rounded-2xl border border-orange-200 bg-orange-50/40 p-5">
                        <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-extrabold uppercase tracking-[.14em] text-emerald-700">✓ Verified-stay review</p><h2 class="mt-2 text-lg font-extrabold">Your review</h2></div><p class="text-xl font-extrabold text-orange-600">{{ str_repeat('★', $review->rating) }}<span class="text-orange-200">{{ str_repeat('★', 5 - $review->rating) }}</span></p></div>
                        @if($review->title)<h3 class="mt-4 font-extrabold">{{ $review->title }}</h3>@endif
                        <p class="mt-2 text-sm leading-6 text-slate-700">{{ $review->content }}</p>
                        @if($review->response)<div class="mt-4 rounded-xl bg-white p-4"><p class="text-xs font-extrabold uppercase tracking-wide text-slate-500">Property owner response</p><p class="mt-2 text-sm leading-6 text-slate-700">{{ $review->response->content }}</p></div>@endif
                    </section>
                @elseif($status === 'completed' && ! $reviewInvitationExpired)
                    <section class="rounded-2xl border border-orange-200 bg-gradient-to-br from-orange-50 to-white p-5" x-data="{ rating: {{ (int) old('rating', 0) }} }">
                        <p class="text-xs font-extrabold uppercase tracking-[.14em] text-orange-600">Share your experience</p><h2 class="mt-2 text-xl font-extrabold">How was your stay?</h2><p class="mt-1 text-sm text-slate-600">Your feedback will be marked as a verified stay because this booking was completed on the platform.</p>
                        <form method="POST" action="{{ route('guest.bookings.reviews.store', $booking) }}" class="mt-5 space-y-4">@csrf
                            <div><p class="text-sm font-bold">Overall rating</p><div class="mt-2 flex gap-2"><template x-for="star in 5"><button type="button" @click="rating=star" class="text-3xl transition hover:scale-110" :class="star<=rating?'text-orange-500':'text-slate-200'" :aria-label="star+' stars'">★</button></template></div><input type="hidden" name="rating" :value="rating"></div>
                            <div class="grid gap-3 sm:grid-cols-2">@foreach(['cleanliness_rating'=>'Cleanliness','communication_rating'=>'Communication','location_rating'=>'Location','value_rating'=>'Value','accuracy_rating'=>'Accuracy'] as $name=>$label)<label class="text-xs font-bold text-slate-700">{{ $label }}<select name="{{ $name }}" class="mt-1 w-full rounded-xl border-orange-200 bg-white text-sm"><option value="">Not rated</option>@foreach(range(5,1) as $score)<option value="{{ $score }}" @selected((string)old($name)===(string)$score)>{{ $score }} – {{ $score===5?'Excellent':($score===4?'Very good':($score===3?'Good':($score===2?'Fair':'Poor'))) }}</option>@endforeach</select></label>@endforeach</div>
                            <label class="block text-xs font-bold text-slate-700">Review title <span class="font-normal text-slate-400">(optional)</span><input name="title" maxlength="120" value="{{ old('title') }}" placeholder="Sum up your stay" class="mt-1 w-full rounded-xl border-orange-200 bg-white text-sm"></label>
                            <label class="block text-xs font-bold text-slate-700">Your review<textarea name="content" required minlength="20" maxlength="3000" rows="5" placeholder="What stood out? What should future guests know?" class="mt-1 w-full rounded-xl border-orange-200 bg-white text-sm">{{ old('content') }}</textarea></label>
                            <button :disabled="rating<1" class="w-full rounded-xl bg-orange-600 px-5 py-3 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-40">Publish verified review</button>
                        </form>
                    </section>
                @elseif($status === 'completed' && $reviewInvitationExpired)
                    <section class="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 class="font-extrabold">Review window closed</h2><p class="mt-2 text-sm text-slate-500">Verified-stay reviews can be submitted within 30 days of invitation.</p></section>
                @endif
            </div>
            <aside class="space-y-5 lg:sticky lg:top-24"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-extrabold">Payment summary</h2><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between text-slate-600"><span>Stay subtotal</span><strong class="text-slate-900">₦{{ number_format((float)$booking->subtotal_amount) }}</strong></div>@if((float)$booking->discount_amount > 0)<div class="flex justify-between text-emerald-700"><span>Stay discount</span><strong>−₦{{ number_format((float)$booking->discount_amount) }}</strong></div>@endif<div class="flex items-center justify-between border-t border-slate-200 pt-4"><span class="font-extrabold">Total</span><strong class="text-xl text-orange-600">₦{{ number_format((float)$booking->total_amount) }}</strong></div><div class="flex justify-between text-emerald-700"><span>Paid</span><strong>₦{{ number_format($paid) }}</strong></div>@if($refunded>0)<div class="flex justify-between text-amber-700"><span>Refunded</span><strong>₦{{ number_format($refunded) }}</strong></div>@endif<div class="flex justify-between text-slate-700"><span>Outstanding</span><strong>₦{{ number_format($outstanding) }}</strong></div></div><div class="mt-5 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><div class="flex justify-between"><span>Payment status</span><strong class="text-slate-800">{{ str($booking->payment_status->value)->replace('_', ' ')->title() }}</strong></div>@if($payment)<div class="mt-2 flex justify-between gap-3"><span>Payment reference</span><strong class="truncate text-slate-800">{{ $payment->reference }}</strong></div>@endif</div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-extrabold">Manage booking</h2><div class="mt-4 space-y-2"><a href="{{ route('guest.bookings.messages.show', $booking) }}" class="block w-full rounded-xl border border-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-800">Message property team</a><a href="{{ route('guest.bookings.receipt',$booking) }}" class="block w-full rounded-xl border border-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-800">Print / save receipt</a>@if($status === 'confirmed')<button type="button" @click="cancelOpen=true" class="w-full rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-600 hover:bg-red-50">Cancel booking</button>@endif</div>@if($status === 'cancelled' && $booking->cancellations->isNotEmpty())<div class="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700"><strong>Cancellation reason</strong><p class="mt-1">{{ $booking->cancellations->last()->reason ?: 'No reason provided.' }}</p></div>@endif</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-extrabold">Booking timeline</h2><ol class="mt-5 space-y-4 border-l border-slate-200 pl-5"><li class="relative"><span class="absolute -left-[25px] top-1 size-2.5 rounded-full bg-orange-500 ring-4 ring-orange-50"></span><p class="text-sm font-bold">Booking created</p><p class="text-xs text-slate-400">{{ $booking->created_at->format('d M Y, H:i') }}</p></li>@foreach($booking->statusHistory->sortBy('created_at')->take(4) as $history)<li class="relative"><span class="absolute -left-[25px] top-1 size-2.5 rounded-full bg-slate-400 ring-4 ring-white"></span><p class="text-sm font-bold">{{ str($history->to_status ?? $history->status ?? 'Updated')->replace('_', ' ')->title() }}</p><p class="text-xs text-slate-400">{{ $history->created_at->format('d M Y, H:i') }}</p></li>@endforeach<li class="relative"><span class="absolute -left-[25px] top-1 size-2.5 rounded-full bg-emerald-500 ring-4 ring-emerald-50"></span><p class="text-sm font-bold">Current status: {{ str($status)->replace('_', ' ')->title() }}</p></li></ol></section></aside>
    </div>

    @if($status === 'confirmed')
    <div x-show="cancelOpen" x-cloak @keydown.escape.window="if(!cancelling) cancelOpen=false" class="fixed inset-0 z-[90] flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="cancel-title">
        <button type="button" @click="cancelOpen=false" class="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" aria-label="Close cancellation confirmation"></button>
        <form method="POST" action="{{ route('guest.bookings.cancel', $booking) }}" @submit="cancelling=true" class="relative w-full max-w-md overflow-hidden rounded-3xl bg-white shadow-2xl">@csrf
            <div class="p-6"><div class="flex size-12 items-center justify-center rounded-full bg-red-100 text-red-600"><svg class="size-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 4h.01M10.3 3.7L2.5 17.2A2 2 0 004.2 20h15.6a2 2 0 001.7-2.8L13.7 3.7a2 2 0 00-3.4 0z"/></svg></div><h2 id="cancel-title" class="mt-4 text-2xl font-extrabold text-slate-950">Cancel this booking?</h2><p class="mt-2 text-sm leading-6 text-slate-600">This will release {{ $nights }} nights at {{ $property->name }}. This action cannot be undone.</p><div class="mt-4 rounded-xl p-3 text-sm font-semibold {{ $isRefundable ? 'bg-emerald-50 text-emerald-800' : 'bg-red-50 text-red-800' }}">{{ $isRefundable ? 'You are cancelling more than 48 hours before check-in, so the full payment is eligible for refund.' : 'This booking is within 48 hours of check-in and is not eligible for a refund.' }}</div><label class="mt-5 block text-sm font-bold text-slate-800">Reason for cancellation <span class="font-normal text-slate-400">(optional)</span><textarea name="reason" rows="3" maxlength="1000" class="mt-2 w-full rounded-xl border-slate-300 text-sm focus:border-red-400 focus:ring-red-400" placeholder="Tell us why your plans changed"></textarea></label><div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" @click="cancelOpen=false" :disabled="cancelling" class="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700">Keep booking</button><button type="submit" :disabled="cancelling" class="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60" x-text="cancelling ? 'Cancelling…' : 'Yes, cancel booking'"></button></div></div>
        </form>
    </div>
    @endif
</div>
</main>
@endsection
