@extends('layouts.admin', ['title' => 'Open dispute', 'pageTitle' => 'Open dispute case'])

@section('content')
<div class="mx-auto max-w-4xl space-y-5"><a href="{{ route('admin.disputes.index') }}" class="inline-flex text-sm font-black text-orange-600">← Dispute management</a><section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="max-w-2xl"><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">Internal case creation</p><h2 class="mt-2 text-2xl font-black">Start from an existing booking</h2><p class="mt-2 text-sm leading-6 text-slate-500">This records an investigation case only. It never charges, refunds or changes a payment.</p></div><form method="POST" action="{{ route('admin.disputes.store') }}" class="mt-7 grid gap-5 sm:grid-cols-2">@csrf
    <label class="sm:col-span-2 text-sm font-black">Booking<select name="booking_id" required class="mt-2 block w-full rounded-xl border-slate-200 text-sm"><option value="">Choose booking</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected(old('booking_id',$selectedBooking)===$booking->id)>{{ $booking->reference }} · {{ $booking->property->name }} · {{ $booking->guest->name }}</option>@endforeach</select></label>
    <label class="text-sm font-black">Case type<select name="dispute_type" required class="mt-2 block w-full rounded-xl border-slate-200 text-sm">@foreach(['guest_complaint'=>'Guest complaint','property_condition'=>'Property condition','payment'=>'Payment','cancellation'=>'Cancellation','safety'=>'Safety','other'=>'Other'] as $value=>$label)<option value="{{ $value }}" @selected(old('dispute_type')===$value)>{{ $label }}</option>@endforeach</select></label>
    <label class="text-sm font-black">Priority<select name="priority" required class="mt-2 block w-full rounded-xl border-slate-200 text-sm">@foreach(['normal','low','high','urgent'] as $value)<option value="{{ $value }}" @selected(old('priority','normal')===$value)>{{ str($value)->title() }}</option>@endforeach</select></label>
    <label class="sm:col-span-2 text-sm font-black">Case description<textarea name="description" required minlength="20" maxlength="4000" rows="5" class="mt-2 block w-full rounded-xl border-slate-200 text-sm" placeholder="Describe the complaint, evidence received and impact…">{{ old('description') }}</textarea></label>
    <label class="text-sm font-black">Disputed amount <span class="font-medium text-slate-400">(optional)</span><input type="number" min="0" step="0.01" name="disputed_amount" value="{{ old('disputed_amount') }}" class="mt-2 block w-full rounded-xl border-slate-200 text-sm"></label>
    <label class="text-sm font-black">Due date <span class="font-medium text-slate-400">(optional)</span><input type="datetime-local" name="due_at" value="{{ old('due_at') }}" class="mt-2 block w-full rounded-xl border-slate-200 text-sm"></label>
    <label class="sm:col-span-2 text-sm font-black">Assign to <span class="font-medium text-slate-400">(optional)</span><select name="assigned_to" class="mt-2 block w-full rounded-xl border-slate-200 text-sm"><option value="">Leave unassigned</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected(old('assigned_to')===$assignee->id)>{{ $assignee->name }} · {{ $assignee->email }}</option>@endforeach</select></label>
    <label class="sm:col-span-2 text-sm font-black">Opening note<textarea name="note" required minlength="10" maxlength="2000" rows="3" class="mt-2 block w-full rounded-xl border-slate-200 text-sm" placeholder="Record why the platform is opening this case now…">{{ old('note') }}</textarea></label>
    <div class="sm:col-span-2 flex justify-end"><button class="rounded-xl bg-orange-600 px-6 py-3 text-sm font-black text-white">Open dispute case</button></div>
</form></section></div>
@endsection
