@extends('layouts.admin', ['title' => 'Dispute management', 'pageTitle' => 'Dispute management'])

@section('content')
@php $canManage=app(\App\Services\PlatformPermissionService::class)->allows(auth()->user(),'platform.dispute.manage'); @endphp
<div class="mx-auto max-w-7xl space-y-5">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-slate-500">Evidence-led booking cases with controlled decisions and a permanent timeline.</p><p class="mt-1 text-xs text-slate-400">{{ number_format($disputes->total()) }} dispute cases</p></div>@if($canManage)<a href="{{ route('admin.disputes.create') }}" class="rounded-xl bg-orange-600 px-5 py-3 text-center text-sm font-black text-white">Open dispute</a>@endif</div>
    <form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_12rem_10rem_auto]"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Case or booking reference" class="rounded-xl border-slate-200 text-sm focus:border-orange-400 focus:ring-orange-200"><select name="status" class="rounded-xl border-slate-200 text-sm"><option value="">All statuses</option>@foreach(['open','under_review','awaiting_guest','awaiting_business','resolved','rejected','closed'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><select name="priority" class="rounded-xl border-slate-200 text-sm"><option value="">Any priority</option>@foreach(['urgent','high','normal','low'] as $priority)<option value="{{ $priority }}" @selected(($filters['priority']??'')===$priority)>{{ str($priority)->title() }}</option>@endforeach</select><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Apply filters</button></form>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="hidden grid-cols-[1fr_1fr_.65fr_.8fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[11px] font-black uppercase tracking-wider text-slate-500 md:grid"><span>Case</span><span>Booking & stay</span><span>Priority</span><span>Owner</span><span></span></div><div class="divide-y divide-slate-100">@forelse($disputes as $dispute)<article class="grid gap-4 px-5 py-4 hover:bg-slate-50 md:grid-cols-[1fr_1fr_.65fr_.8fr_auto] md:items-center"><div><p class="text-sm font-black">{{ $dispute->reference }}</p><p class="mt-1 text-xs text-slate-500">{{ str($dispute->dispute_status->value)->replace('_',' ')->title() }} @if($dispute->due_at && $dispute->due_at->isPast() && !in_array($dispute->dispute_status->value,['closed','resolved','rejected'])) · <span class="font-bold text-red-600">Overdue</span>@endif</p></div><div><p class="text-sm font-bold">{{ $dispute->property->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $dispute->booking->reference }} · {{ $dispute->booking->guest->name }}</p></div><span class="w-fit rounded-full px-2.5 py-1 text-[11px] font-black {{ in_array($dispute->priority,['urgent','high'])?'bg-red-100 text-red-800':'bg-slate-100 text-slate-700' }}">{{ str($dispute->priority)->title() }}</span><p class="text-sm font-bold">{{ $dispute->assignee?->name ?? 'Unassigned' }}</p><a href="{{ route('admin.disputes.show',$dispute) }}" class="rounded-xl bg-orange-600 px-4 py-2 text-center text-sm font-black text-white">Open case</a></article>@empty<div class="p-12 text-center"><p class="font-bold text-slate-700">No dispute cases match these filters.</p><p class="mt-1 text-sm text-slate-500">Platform administrators create cases from real booking records.</p></div>@endforelse</div></section>{{ $disputes->links() }}
</div>
@endsection
