@extends('layouts.admin', ['title' => $dispute->reference, 'pageTitle' => 'Dispute case'])

@section('content')
@php
    $canManage=app(\App\Services\PlatformPermissionService::class)->allows(auth()->user(),'platform.dispute.manage');
    $current=$dispute->dispute_status->value;
    $next=['open'=>['under_review'], 'under_review'=>['awaiting_guest','awaiting_business','resolved','rejected'], 'awaiting_guest'=>['under_review'], 'awaiting_business'=>['under_review'], 'resolved'=>['closed'], 'rejected'=>['closed'], 'closed'=>[]][$current] ?? [];
@endphp
<div class="mx-auto max-w-7xl space-y-5" x-data="{ transitionOpen: false }">
    <a href="{{ route('admin.disputes.index') }}" class="inline-flex text-sm font-black text-orange-600">← Dispute management</a>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex flex-col justify-between gap-5 lg:flex-row"><div><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">{{ $dispute->reference }}</p><h2 class="mt-2 text-2xl font-black">{{ str($dispute->dispute_type)->replace('_',' ')->title() }}</h2><p class="mt-2 text-sm text-slate-500">Opened {{ $dispute->opened_at->format('d M Y, H:i') }} by {{ $dispute->opener?->name ?? 'Platform' }}</p></div><div class="flex flex-wrap items-start gap-2"><span class="rounded-full bg-slate-950 px-3 py-1.5 text-xs font-black text-white">{{ str($current)->replace('_',' ')->title() }}</span><span class="rounded-full px-3 py-1.5 text-xs font-black {{ in_array($dispute->priority,['urgent','high'])?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800' }}">{{ str($dispute->priority)->title() }}</span></div></div><div class="mt-6 rounded-2xl bg-slate-50 p-5"><p class="whitespace-pre-line text-sm leading-7 text-slate-700">{{ $dispute->description }}</p></div>@if($dispute->resolution)<div class="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p class="text-xs font-black uppercase tracking-widest text-emerald-700">Recorded resolution</p><p class="mt-2 text-sm leading-6 text-emerald-950">{{ $dispute->resolution }}</p>@if($dispute->approved_amount!==null)<p class="mt-3 text-sm font-black text-emerald-800">Approved record: {{ $dispute->currency }} {{ number_format((float)$dispute->approved_amount,2) }} <span class="font-medium">— not paid in this MVP</span></p>@endif</div>@endif</section>
    <div class="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div class="space-y-5"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">Booking context</h3><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Booking</dt><dd class="font-black">{{ $dispute->booking->reference }}</dd></div><div><dt class="text-slate-500">Guest</dt><dd class="font-black">{{ $dispute->booking->guest->name }}</dd></div><div><dt class="text-slate-500">Property</dt><dd class="font-black">{{ $dispute->property->name }}</dd></div><div><dt class="text-slate-500">Business</dt><dd class="font-black">{{ $dispute->business->name }}</dd></div><div><dt class="text-slate-500">Stay</dt><dd class="font-black">{{ $dispute->booking->arrival_date->format('d M Y') }} – {{ $dispute->booking->departure_date->format('d M Y') }}</dd></div><div><dt class="text-slate-500">Booking total</dt><dd class="font-black">{{ $dispute->booking->currency }} {{ number_format((float)$dispute->booking->total_amount,2) }}</dd></div></dl></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">Financial and support evidence</h3><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">Payments</p><p class="mt-1 text-xl font-black">{{ $dispute->booking->payments->count() }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">Cancellations</p><p class="mt-1 text-xl font-black">{{ $dispute->booking->cancellations->count() }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">Service requests</p><p class="mt-1 text-xl font-black">{{ $dispute->booking->serviceRequests->count() }}</p></div></div><p class="mt-4 text-xs font-bold text-slate-400">Case decisions never mutate payment or refund records in this simulated-payment MVP.</p></section></div>
        <aside class="space-y-5">@if($canManage)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">Case ownership</h3><form method="POST" action="{{ route('admin.disputes.assign',$dispute) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<select name="assigned_to" required class="block w-full rounded-xl border-slate-200 text-sm">@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected($dispute->assigned_to===$assignee->id)>{{ $assignee->name }}</option>@endforeach</select><textarea name="note" required minlength="10" rows="3" class="block w-full rounded-xl border-slate-200 text-sm" placeholder="Why is this assignment changing?"></textarea><button class="w-full rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Update assignment</button></form></section>@if($next)<section class="rounded-2xl border border-orange-200 bg-orange-50 p-5"><h3 class="font-black">Move the case forward</h3><form method="POST" action="{{ route('admin.disputes.transition',$dispute) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<select name="status" required x-ref="nextStatus" class="block w-full rounded-xl border-orange-200 bg-white text-sm">@foreach($next as $status)<option value="{{ $status }}">{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><textarea name="note" required minlength="10" rows="3" class="block w-full rounded-xl border-orange-200 bg-white text-sm" placeholder="Case note explaining this transition…"></textarea>@if(in_array('resolved',$next)||in_array('rejected',$next))<textarea name="resolution" rows="4" class="block w-full rounded-xl border-orange-200 bg-white text-sm" placeholder="Required when resolving or rejecting: record the final decision…"></textarea><input type="number" min="0" step="0.01" name="approved_amount" class="block w-full rounded-xl border-orange-200 bg-white text-sm" placeholder="Approved amount (record only, optional)">@endif<button class="w-full rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-black text-white">Update case status</button></form></section>@endif @endif</aside></div>
    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Immutable case timeline</h3></div><div class="divide-y divide-slate-100">@forelse($dispute->audits->sortByDesc('occurred_at') as $event)<div class="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold">{{ $event->description }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name }} · {{ data_get($event->metadata,'reason') }}</p></div><time class="text-xs text-slate-400">{{ $event->occurred_at?->format('d M Y, H:i') }}</time></div>@empty<div class="p-8 text-center text-sm text-slate-500">No case actions recorded.</div>@endforelse</div></section>
</div>
@endsection
