<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Team & access – {{ $business->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
@php
    $permissions = app(\App\Services\Access\BusinessPermissionService::class);
    $canChangeRoles = $permissions->allows(auth()->user(), $activeBusinessContext, 'employee.change_role');
    $canRemove = $permissions->allows(auth()->user(), $activeBusinessContext, 'employee.remove');
    $viewerIsOwner = auth()->user()->hasActiveBusinessRole('business_owner', $activeBusinessContext->membership->id);
@endphp
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased" x-data="{sidebarOpen:false,addOpen:false}">
<div class="flex min-h-screen">@include('partials.sidebar-nav',['active'=>'team'])<div class="min-w-0 flex-1">
<header class="border-b border-slate-200 bg-white px-4 py-4 lg:px-8"><div class="flex items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">People and permissions</p><h1 class="mt-1 text-xl font-extrabold">Team & access</h1></div><button type="button" @click="addOpen=true" class="rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-extrabold text-white shadow-sm hover:bg-orange-700">Add team member</button></div></header>
<main class="mx-auto max-w-[1200px] px-4 py-6 lg:px-6">
    @if(session('status'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-extrabold">The access change could not be saved.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Team records</p><p class="mt-2 text-3xl font-extrabold">{{ $memberships->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Active access</p><p class="mt-2 text-3xl font-extrabold text-emerald-700">{{ $memberships->where('status.value','active')->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Available roles</p><p class="mt-2 text-3xl font-extrabold text-orange-600">{{ $roles->count() }}</p></div></section>

    <section class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-extrabold">Business access</h2><p class="mt-1 text-xs text-slate-500">Roles control actions. Property assignments narrow access when a team member is scoped to selected properties.</p></div>
        <div class="divide-y divide-slate-100">@forelse($memberships as $membership)
            @php
                $assignment = $membership->roles->first(fn($item)=>$item->status->value==='active' && !$item->revoked_at);
                $role = $assignment?->role;
                $assignedIds = $membership->employee?->propertyAssignments->where('assignment_status','active')->where('status','active')->pluck('property_id')->all() ?? [];
                $active = $membership->status->value === 'active';
            @endphp
            <article class="p-5" x-data="{editOpen:false,removeOpen:false}"><div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div class="flex min-w-0 items-start gap-3"><div class="flex size-11 shrink-0 items-center justify-center rounded-full bg-orange-100 text-sm font-extrabold text-orange-700">{{ str($membership->user->name)->explode(' ')->map(fn($part)=>str($part)->substr(0,1))->take(2)->join('') }}</div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="font-extrabold">{{ $membership->user->name }}</h3><span class="rounded-full px-2.5 py-1 text-[10px] font-extrabold {{ $active?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600' }}">{{ str($membership->status->value)->title() }}</span></div><p class="mt-1 text-sm text-slate-500">{{ $membership->user->email }}</p><p class="mt-2 text-xs font-bold text-orange-700">{{ $role?->name ?? 'No active role' }}@if($membership->job_title) · {{ $membership->job_title }}@endif</p><div class="mt-2 flex flex-wrap gap-1.5">@forelse($membership->employee?->propertyAssignments->where('assignment_status','active')->where('status','active') ?? collect() as $propertyAssignment)<span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{{ $propertyAssignment->property->name }}</span>@empty<span class="text-[11px] text-slate-400">Business-wide access within role permissions</span>@endforelse</div></div></div>
                <div class="flex gap-2">@if($canChangeRoles && $active)<button type="button" @click="editOpen=!editOpen" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:bg-slate-50">Edit access</button>@endif @if($canRemove && $active && $membership->user_id!==auth()->id())<button type="button" @click="removeOpen=true" class="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700 hover:bg-red-50">Deactivate</button>@endif</div></div>
                @if($canChangeRoles && $active)<form x-show="editOpen" x-cloak method="POST" action="{{ route('owner.team.update',$membership) }}" class="mt-5 rounded-xl border border-orange-200 bg-orange-50/40 p-4">@csrf @method('PATCH')<div class="grid gap-3 md:grid-cols-2"><label class="text-xs font-bold">Job title<input name="job_title" value="{{ $membership->job_title }}" maxlength="120" class="mt-1 w-full rounded-lg border-orange-200 bg-white text-sm"></label><label class="text-xs font-bold">Role<select name="role_id" required class="mt-1 w-full rounded-lg border-orange-200 bg-white text-sm">@foreach($roles as $option)@if($viewerIsOwner || $option->system_key!=='business_owner')<option value="{{ $option->id }}" @selected($role?->id===$option->id)>{{ $option->name }}</option>@endif @endforeach</select></label></div><fieldset class="mt-4"><legend class="text-xs font-bold">Property scope <span class="font-normal text-slate-400">(leave empty for business-wide access)</span></legend><div class="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($properties as $property)<label class="flex items-center gap-2 rounded-lg border border-orange-100 bg-white p-2 text-xs font-semibold"><input type="checkbox" name="property_ids[]" value="{{ $property->id }}" @checked(in_array($property->id,$assignedIds,true)) class="rounded border-orange-300 text-orange-600">{{ $property->name }}</label>@endforeach</div></fieldset><div class="mt-4 flex justify-end gap-2"><button type="button" @click="editOpen=false" class="rounded-lg border px-4 py-2 text-xs font-bold">Cancel</button><button class="rounded-lg bg-orange-600 px-4 py-2 text-xs font-extrabold text-white">Save access</button></div></form>@endif
                @if($canRemove && $membership->user_id!==auth()->id())<div x-show="removeOpen" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button type="button" @click="removeOpen=false" class="absolute inset-0 bg-slate-950/60" aria-label="Close"></button><form method="POST" action="{{ route('owner.team.deactivate',$membership) }}" class="relative w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl">@csrf @method('DELETE')<div class="flex size-11 items-center justify-center rounded-full bg-red-100 font-extrabold text-red-700">!</div><h2 class="mt-4 text-xl font-extrabold">Deactivate {{ $membership->user->name }}?</h2><p class="mt-2 text-sm leading-6 text-slate-600">Their business context, active roles and staff access will be disabled. Historical task records remain intact.</p><div class="mt-5 flex justify-end gap-2"><button type="button" @click="removeOpen=false" class="rounded-lg border px-4 py-2 text-sm font-bold">Keep access</button><button class="rounded-lg bg-red-600 px-4 py-2 text-sm font-bold text-white">Deactivate access</button></div></form></div>@endif
            </article>
        @empty<div class="p-12 text-center text-sm text-slate-500">No business memberships found.</div>@endforelse</div>
    </section>
</main></div></div>

<div x-show="addOpen" x-cloak @keydown.escape.window="addOpen=false" class="fixed inset-0 z-[90] flex items-center justify-center p-4"><button type="button" @click="addOpen=false" class="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" aria-label="Close"></button><form method="POST" action="{{ route('owner.team.store') }}" class="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl">@csrf<div class="flex items-start justify-between"><div><p class="text-xs font-extrabold uppercase tracking-wide text-orange-600">Team access</p><h2 class="mt-2 text-2xl font-extrabold">Add a team member</h2><p class="mt-1 text-sm text-slate-500">New users receive a secure password-setup email. Existing accounts are connected directly.</p></div><button type="button" @click="addOpen=false" class="flex size-9 items-center justify-center rounded-full bg-slate-100 text-xl">×</button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="text-xs font-bold">Full name<input name="name" required maxlength="120" value="{{ old('name') }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-xs font-bold">Email address<input name="email" type="email" required value="{{ old('email') }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-xs font-bold">Job title<input name="job_title" maxlength="120" value="{{ old('job_title') }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-xs font-bold">Role<select name="role_id" required class="mt-1 w-full rounded-xl border-slate-200"><option value="">Choose role</option>@foreach($roles as $role)@if($viewerIsOwner || $role->system_key!=='business_owner')<option value="{{ $role->id }}">{{ $role->name }}</option>@endif @endforeach</select></label></div><fieldset class="mt-5"><legend class="text-xs font-bold">Assign specific properties <span class="font-normal text-slate-400">(optional)</span></legend><p class="mt-1 text-xs text-slate-500">Selecting properties limits property-specific access to those records.</p><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($properties as $property)<label class="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="property_ids[]" value="{{ $property->id }}" class="rounded border-orange-300 text-orange-600">{{ $property->name }}</label>@endforeach</div></fieldset><div class="mt-6 flex justify-end gap-3"><button type="button" @click="addOpen=false" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">Cancel</button><button class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-extrabold text-white">Add member & send setup</button></div></form></div>
</body></html>
