@extends('layouts.admin', ['title' => $user->name, 'pageTitle' => 'Account security'])

@section('content')
@php
    $permissions=app(\App\Services\PlatformPermissionService::class);
    $canLock=$permissions->allows(auth()->user(),'platform.user.lock') && auth()->id()!==$user->id;
    $platformRole=$user->roleAssignments->first(fn($assignment)=>$assignment->role?->scope->value==='platform' && $assignment->status->value==='active')?->role;
    $isLocked=$user->status->value==='suspended' || $user->locked_until?->isFuture();
@endphp
<div class="mx-auto max-w-6xl space-y-5" x-data="{ securityAction: null }">
    <a href="{{ route('admin.users.index') }}" class="inline-flex text-sm font-black text-orange-600">← User directory</a>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex flex-col justify-between gap-5 sm:flex-row"><div><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">{{ $platformRole?->name ?? ($user->business_memberships_count ? 'Business account' : 'Guest account') }}</p><h2 class="mt-2 text-3xl font-black">{{ $user->name }}</h2><p class="mt-2 text-sm text-slate-500">{{ $user->email }}{{ $user->phone_number ? ' · '.$user->phone_number : '' }}</p></div>@if($canLock)<div>@if($isLocked)<button @click="securityAction='unlock'" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Unlock account</button>@else<button @click="securityAction='lock'" class="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-black text-white">Lock account</button>@endif</div>@endif</div>
        @if($isLocked)<div class="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Account access is restricted.</strong> Active database sessions have been terminated and new authentication is denied.</div>@endif
        <dl class="mt-7 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs font-bold text-slate-500">Identity verification</dt><dd class="mt-1 font-black">{{ str($user->identity_verification_status->value)->title() }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Failed logins</dt><dd class="mt-1 font-black">{{ $user->failed_login_attempts }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Last login</dt><dd class="mt-1 font-black">{{ $user->last_login_at?->format('d M Y, H:i') ?? 'Never' }}</dd></div><div><dt class="text-xs font-bold text-slate-500">Last activity</dt><dd class="mt-1 font-black">{{ $user->last_seen_at?->diffForHumans() ?? 'No activity' }}</dd></div></dl>
    </section>
    <div class="grid gap-5 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Business memberships</h3></div><div class="divide-y divide-slate-100">@forelse($user->businessMemberships as $membership)<div class="px-5 py-4"><div class="flex justify-between gap-4"><div><p class="text-sm font-black">{{ $membership->business->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $membership->roles->map(fn($assignment)=>$assignment->role?->name)->filter()->join(', ') ?: 'No role' }}</p></div><span class="text-xs font-bold text-slate-400">{{ str($membership->status->value)->title() }}</span></div></div>@empty<div class="p-8 text-center text-sm text-slate-500">No business memberships.</div>@endforelse</div></section><section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black">Security history</h3></div><div class="divide-y divide-slate-100">@forelse($audits as $event)<div class="px-5 py-4"><p class="text-sm font-bold">{{ $event->description }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name }} · {{ data_get($event->metadata,'reason') }}</p><time class="mt-1 block text-[11px] text-slate-400">{{ $event->occurred_at?->format('d M Y, H:i') }}</time></div>@empty<div class="p-8 text-center text-sm text-slate-500">No security actions recorded.</div>@endforelse</div></section></div>
    @if($canLock)<div x-cloak x-show="securityAction" class="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm"><div class="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" @click.outside="securityAction=null"><div class="flex justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-widest text-orange-600">Security confirmation</p><h3 class="mt-2 text-xl font-black" x-text="securityAction==='lock'?'Lock this account?':'Restore this account?' "></h3></div><button @click="securityAction=null" class="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div><p class="mt-3 text-sm leading-6 text-slate-600" x-text="securityAction==='lock'?'All database sessions will end immediately and login will be blocked.':'Login access will resume and failed attempts will reset.'"></p><form method="POST" :action="'{{ url('/admin/users/'.$user->id) }}/'+securityAction" class="mt-5">@csrf<textarea name="reason" required minlength="10" maxlength="1000" rows="4" class="block w-full rounded-xl border-slate-200 text-sm focus:border-orange-400 focus:ring-orange-200" placeholder="State the security evidence and reason…"></textarea><div class="mt-5 flex justify-end gap-2"><button type="button" @click="securityAction=null" class="rounded-xl px-4 py-2.5 text-sm font-black text-slate-600">Cancel</button><button class="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white hover:bg-orange-600">Confirm security action</button></div></form></div></div>@endif
</div>
@endsection
