@extends('layouts.admin')
@section('title','Settlements')
@section('content')
<div class="space-y-6">
 <div><p class="text-xs font-black uppercase tracking-[.18em] text-orange-600">Platform finance</p><h1 class="mt-2 text-3xl font-black">Owner settlements</h1><p class="mt-2 text-sm text-slate-500">Verified balances, separated approval and traceable bank transfers.</p></div>
 @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{session('status')}}</div>@endif
 @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{$errors->first()}}</div>@endif
 <form method="GET" class="rounded-2xl border bg-white p-5"><label class="text-xs font-black uppercase text-slate-500">Business<select name="business" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select business</option>@foreach($businesses as $item)<option value="{{$item->id}}" @selected($business?->id===$item->id)>{{$item->name}}</option>@endforeach</select></label></form>
 @if($business)
 <div class="grid gap-5 xl:grid-cols-2">
  <section class="rounded-2xl border bg-white p-5"><h2 class="font-black">Settlement destination</h2><p class="mt-1 text-xs text-slate-500">Account numbers are encrypted and only the last four digits are displayed.</p><form method="POST" action="{{route('admin.settlements.account',$business)}}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="bank_name" required placeholder="Bank name" class="rounded-xl border-slate-300"><input name="account_name" required placeholder="Account name" class="rounded-xl border-slate-300"><input name="account_number" required inputmode="numeric" placeholder="Account number" class="rounded-xl border-slate-300 sm:col-span-2"><button class="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white sm:col-span-2">Verify destination</button></form>@if($account)<p class="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{{$account->bank_name}} · {{$account->masked_number}}</p>@endif</section>
  <section class="rounded-2xl border bg-white p-5"><h2 class="font-black">Available owner balances</h2><form method="POST" action="{{route('admin.settlements.store',$business)}}" class="mt-4 space-y-3">@csrf @forelse($available as $entry)<label class="flex items-center justify-between rounded-xl border p-3"><span><b>{{number_format((float)$entry->amount,2)}} {{$entry->currency}}</b><small class="block text-slate-500">{{$entry->recognized_on->format('d M Y')}} · {{$entry->description}}</small></span><input type="checkbox" name="allocations[]" value="{{$entry->id}}" class="rounded border-slate-300 text-orange-600"></label>@empty<p class="text-sm text-slate-500">No unsettled owner balances.</p>@endforelse @if($available->isNotEmpty())<button class="w-full rounded-xl bg-orange-600 px-4 py-3 text-sm font-black text-white">Create settlement batch</button>@endif</form></section>
 </div>
 <section class="overflow-hidden rounded-2xl border bg-white"><div class="border-b p-5"><h2 class="font-black">Settlement history</h2></div><div class="divide-y">@forelse($batches as $batch)<article class="p-5"><div class="flex flex-wrap justify-between gap-3"><div><b>{{$batch->reference}}</b><p class="text-sm text-slate-500">{{number_format((float)$batch->amount,2)}} {{$batch->currency}} · {{str($batch->settlement_status)->title()}}</p></div><div class="flex flex-wrap gap-2">@if($batch->settlement_status==='draft')<form method="POST" action="{{route('admin.settlements.approve',$batch)}}">@csrf<button class="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white">Approve</button></form>@elseif($batch->settlement_status==='approved')<form method="POST" action="{{route('admin.settlements.complete',$batch)}}" class="flex gap-2">@csrf<input name="transfer_reference" required placeholder="Bank transfer reference" class="rounded-lg border-slate-300 text-xs"><button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Complete</button></form>@elseif($batch->settlement_status==='completed')<form method="POST" action="{{route('admin.settlements.reverse',$batch)}}" class="flex gap-2">@csrf<input name="reason" required minlength="10" placeholder="Reversal reason" class="rounded-lg border-slate-300 text-xs"><button class="rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white">Reverse</button></form>@endif</div></div></article>@empty<p class="p-8 text-center text-sm text-slate-500">No settlement batches yet.</p>@endforelse</div></section>
 @endif
</div>
@endsection
