<?php

declare(strict_types=1);

if ($argc !== 3) {
    fwrite(STDERR, "Usage: php scripts/generate_schema_dictionary.php <sqlite-database> <output-markdown>\n");
    exit(1);
}

[$script, $databasePath, $outputPath] = $argv;
$database = new PDO('sqlite:'.$databasePath, options: [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

$purposes = [
    'businesses' => 'The tenant and legal/operational organization that owns properties, bookings, employees, finance, operations, and settings.',
    'users' => 'The single identity and authentication record for every person using the platform, regardless of the roles they later adopt.',
    'business_memberships' => 'Connects a user to a business and establishes their tenant membership lifecycle.',
    'roles' => 'Defines system or business-specific roles at public, business, or platform scope.',
    'user_roles' => 'Assigns one or more roles to a user, optionally through a particular business membership.',
    'permissions' => 'Defines atomic actions that roles may be allowed to perform.',
    'properties' => 'The permanent digital profile of an accommodation owned by a business.',
    'bookings' => 'The central reservation record connecting a business, property, guest, dates, occupancy, pricing, and booking/payment state.',
    'payments' => 'An immutable auditable money-transfer record related to a booking, including separate refund transactions.',
    'operational_tasks' => 'A unit of operational work for a property, optionally generated by a booking or workflow.',
    'employees' => 'Business-specific employment information layered on top of a user business membership.',
    'assets' => 'A durable physical item belonging to a property and retained throughout its maintenance history.',
    'documents' => 'Searchable metadata for a business document owned by another platform entity.',
    'notifications' => 'A logical notification addressed to a user and generated by a platform event.',
    'audit_events' => 'An immutable record of a significant action, its actor, source, affected entity, and before/after data.',
    'domain_events' => 'The durable event/outbox record used to coordinate event-driven behavior across modules.',
    'workflow_templates' => 'A reusable, versioned system or business workflow definition.',
    'workflow_runs' => 'One historical execution of a workflow in response to a domain event.',
    'financial_transactions' => 'The immutable business money ledger used for auditable financial reporting.',
    'approval_workflows' => 'A reusable, versioned approval definition for expenses, refunds, publication, AI actions, or other subjects.',
    'approval_requests' => 'A particular approval lifecycle for a polymorphic business subject.',
    'inventory_movements' => 'The immutable stock ledger for receipts, consumption, transfers, returns, damage, and adjustments.',
    'ai_recommendations' => 'An explainable AI recommendation with evidence, lifecycle state, model provenance, and optional executable action.',
];

$commonDescriptions = [
    'id' => 'Globally unique UUID primary key. It is permanent and must not be reused.',
    'business_id' => 'Owning business/tenant. It is the primary boundary for authorization and data isolation.',
    'property_id' => 'Related property UUID.',
    'booking_id' => 'Related booking UUID.',
    'user_id' => 'Related platform user UUID.',
    'employee_id' => 'Related business employee UUID.',
    'status' => 'General lifecycle state, normally active, inactive, or archived. Domain-specific state is stored separately where needed.',
    'created_by' => 'User who created the record. Null is allowed for imports, seeds, and system-generated records.',
    'updated_by' => 'User who last modified the record. Null is allowed for system changes or when the user is no longer retained.',
    'created_at' => 'Timestamp when the database record was created.',
    'updated_at' => 'Timestamp when the database record was last modified.',
    'deleted_at' => 'Soft-deletion timestamp. A value hides the record operationally without physically destroying its history.',
    'name' => 'Human-readable name.',
    'title' => 'Short human-readable title.',
    'description' => 'Longer human-readable explanation of the record.',
    'notes' => 'Internal free-form operational notes.',
    'metadata' => 'Extensible JSON metadata that does not replace normalized relationships.',
    'currency' => 'ISO 4217 currency code used by the monetary fields on the record.',
    'reference' => 'Human-facing or provider-facing reference used to locate and reconcile the record.',
    'code' => 'Stable business-readable code used for searching and uniqueness.',
    'email' => 'Email address associated with the record.',
    'phone_number' => 'Telephone number associated with the record.',
    'address' => 'Structured or serialized address information.',
    'occurred_at' => 'Business timestamp when the represented event actually occurred.',
    'started_at' => 'Timestamp when processing or work began.',
    'completed_at' => 'Timestamp when processing or work completed.',
    'expires_at' => 'Timestamp after which the record, token, authority, or action is no longer valid.',
    'issued_on' => 'Calendar date on which the document, certificate, or item was issued.',
    'effective_on' => 'Calendar date from which the record becomes effective.',
    'expires_on' => 'Calendar date on which the record expires.',
];

$domainRules = [
    'Platform and access control' => ['users', 'password_', 'sessions', 'user_', 'workspaces', 'permissions', 'roles', 'role_', 'permission_', 'impersonation_'],
    'Business and onboarding' => ['businesses', 'business_', 'departments'],
    'Properties and marketplace' => ['properties', 'amenities', 'property_', 'suppliers', 'assets', 'asset_'],
    'Bookings and guest stay' => ['bookings', 'booking_', 'guest_', 'cancellation_'],
    'Calendar and availability' => ['external_calendar_', 'property_availability_'],
    'Payments and finance' => ['payments', 'expenses', 'expense_', 'financial_', 'revenue_', 'refund_', 'currency_', 'tax_', 'cost_centres'],
    'Operations and inventory' => ['employees', 'employee_', 'operational_', 'inspections', 'inspection_', 'maintenance_', 'inventory_'],
    'Documents, notifications, and reviews' => ['documents', 'document_', 'notifications', 'notification_', 'reviews', 'review_'],
    'Events, workflows, and approvals' => ['domain_events', 'workflow_', 'approval_'],
    'Dashboards and AI' => ['dashboard_', 'business_health_', 'ai_'],
    'Governance and framework support' => ['audit_events', 'data_', 'migrations'],
];

function humanize(string $value): string
{
    return str_replace('_', ' ', $value);
}

function purposeFor(string $table, array $purposes): string
{
    if (isset($purposes[$table])) {
        return $purposes[$table];
    }

    $label = humanize($table);
    $prefixes = [
        'ai_' => 'Stores AI workspace records for ',
        'approval_' => 'Stores approval-engine records for ',
        'asset_' => 'Stores asset lifecycle records for ',
        'booking_' => 'Stores booking workspace records for ',
        'business_' => 'Stores business workspace records for ',
        'data_' => 'Stores data-governance records for ',
        'document_' => 'Stores document-management records for ',
        'employee_' => 'Stores workforce records for ',
        'external_calendar_' => 'Stores external calendar integration records for ',
        'financial_' => 'Stores finance workspace records for ',
        'inventory_' => 'Stores inventory-management records for ',
        'notification_' => 'Stores notification delivery records for ',
        'operational_' => 'Stores operational workflow records for ',
        'property_' => 'Stores property workspace records for ',
        'review_' => 'Stores guest-review records for ',
        'workflow_' => 'Stores workflow-engine records for ',
    ];
    foreach ($prefixes as $prefix => $description) {
        if (str_starts_with($table, $prefix)) {
            return $description.humanize(substr($table, strlen($prefix))).'.';
        }
    }

    return 'Stores '.$label.' records used by the platform.';
}

function domainFor(string $table, array $domainRules): string
{
    foreach ($domainRules as $domain => $patterns) {
        foreach ($patterns as $pattern) {
            if ($table === $pattern || str_starts_with($table, $pattern)) {
                return $domain;
            }
        }
    }

    return 'Other platform data';
}

function fieldDescription(string $column, array $foreignKeys, array $commonDescriptions): string
{
    if (isset($commonDescriptions[$column])) {
        return $commonDescriptions[$column];
    }
    if (isset($foreignKeys[$column])) {
        $foreign = $foreignKeys[$column];
        return "Foreign key to `{$foreign['table']}.{$foreign['to']}`; deletion behavior is {$foreign['delete']}";
    }
    $label = humanize($column);
    if (str_starts_with($column, 'is_') || str_starts_with($column, 'has_') || str_starts_with($column, 'requires_') || str_starts_with($column, 'allow_')) {
        return "Boolean flag indicating whether {$label}.";
    }
    if (str_ends_with($column, '_at')) {
        return "Timestamp recording when {$label}.";
    }
    if (str_ends_with($column, '_on') || str_ends_with($column, '_date')) {
        return "Calendar date associated with {$label}.";
    }
    if (str_ends_with($column, '_status')) {
        return "Domain-specific lifecycle or processing state for {$label}.";
    }
    if (str_ends_with($column, '_type') || $column === 'type') {
        return "Classification describing {$label}.";
    }
    if (str_ends_with($column, '_count') || str_ends_with($column, '_number') || str_ends_with($column, '_order') || $column === 'sequence') {
        return "Numeric value used for {$label}.";
    }
    if (str_contains($column, 'amount') || str_contains($column, 'cost') || str_contains($column, 'price') || str_contains($column, 'value') || str_ends_with($column, '_rate') || str_ends_with($column, '_score')) {
        return "Numeric value representing {$label}; interpret it with the table's currency, scale, or scoring context.";
    }
    if (str_contains($column, 'configuration') || str_contains($column, 'preferences') || str_contains($column, 'snapshot') || str_contains($column, 'payload') || str_contains($column, 'evidence') || str_contains($column, 'rules')) {
        return "JSON or structured data containing {$label}.";
    }
    if (str_ends_with($column, '_url') || str_ends_with($column, '_uri') || $column === 'path') {
        return "Location used to access {$label}; file contents normally live outside the relational database.";
    }
    if (str_ends_with($column, '_key') || str_ends_with($column, '_code') || str_ends_with($column, '_reference')) {
        return "Stable identifier used for {$label}.";
    }

    return "Stores the {$label} value for this record.";
}

$tables = $database->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);
$grouped = [];
foreach ($tables as $table) {
    $grouped[domainFor($table, $domainRules)][] = $table;
}

$lines = [
    '# Project Nexus — Exhaustive Schema Data Dictionary',
    '',
    '> Generated from a freshly migrated database by `scripts/generate_schema_dictionary.php`.',
    '',
    'This document lists every active table and every field. SQLite type names shown here are the portable representation Laravel produced during verification; production database engines may render equivalent types differently.',
    '',
    'Legend: **Required** means the column is not nullable. Defaults are database defaults, not application-level defaults. Foreign-key deletion behavior is shown in the field description.',
    '',
    'Total active tables: **'.count($tables).'**.',
    '',
];

foreach ($grouped as $domain => $domainTables) {
    $lines[] = '## '.$domain;
    $lines[] = '';
    foreach ($domainTables as $table) {
        $columns = $database->query('PRAGMA table_info("'.$table.'")')->fetchAll(PDO::FETCH_ASSOC);
        $foreignRows = $database->query('PRAGMA foreign_key_list("'.$table.'")')->fetchAll(PDO::FETCH_ASSOC);
        $foreignKeys = [];
        foreach ($foreignRows as $foreign) {
            $foreignKeys[$foreign['from']] = ['table' => $foreign['table'], 'to' => $foreign['to'], 'delete' => $foreign['on_delete']];
        }
        $indexes = $database->query('PRAGMA index_list("'.$table.'")')->fetchAll(PDO::FETCH_ASSOC);

        $lines[] = '### `'.$table.'`';
        $lines[] = '';
        $lines[] = purposeFor($table, $purposes);
        $lines[] = '';
        $lines[] = '| Field | Database type | Required | Default | Meaning |';
        $lines[] = '|---|---|---:|---|---|';
        foreach ($columns as $column) {
            $default = $column['dflt_value'] === null ? '—' : '`'.str_replace('|', '\\|', (string) $column['dflt_value']).'`';
            $description = fieldDescription($column['name'], $foreignKeys, $commonDescriptions);
            $lines[] = '| `'.$column['name'].'` | `'.$column['type'].'` | '.($column['notnull'] || $column['pk'] ? 'Yes' : 'No').' | '.$default.' | '.str_replace('|', '\\|', $description).' |';
        }
        $lines[] = '';
        if ($indexes !== []) {
            $indexDescriptions = [];
            foreach ($indexes as $index) {
                if (str_starts_with($index['name'], 'sqlite_autoindex')) {
                    continue;
                }
                $indexColumns = $database->query('PRAGMA index_info("'.$index['name'].'")')->fetchAll(PDO::FETCH_ASSOC);
                $names = array_column($indexColumns, 'name');
                $indexDescriptions[] = '`'.$index['name'].'` on (`'.implode('`, `', $names).'`)'.($index['unique'] ? ' — unique' : '');
            }
            if ($indexDescriptions !== []) {
                $lines[] = '**Indexes:** '.implode('; ', $indexDescriptions).'.';
                $lines[] = '';
            }
        }
    }
}

$directory = dirname($outputPath);
if (! is_dir($directory)) {
    mkdir($directory, 0777, true);
}
file_put_contents($outputPath, implode("\n", $lines)."\n");
echo 'Wrote '.count($tables)." tables to {$outputPath}\n";
