<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Property publishing – Verified Shortlet</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-950 antialiased">
<header class="border-b border-slate-200 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">Platform admin</p><h1 class="mt-1 text-xl font-extrabold">Property publishing</h1></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold">Log out</button></form></div></header>
<main class="mx-auto max-w-7xl space-y-5 px-4 py-6 lg:px-8">
@if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
<form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_14rem_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Search property, code or business" class="rounded-lg border-slate-200"><select name="status" class="rounded-lg border-slate-200"><option value="">All statuses</option>@foreach(['draft','pending','published','unpublished'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ str($status)->title() }}</option>@endforeach</select><button class="rounded-lg bg-slate-950 px-5 py-2 text-sm font-bold text-white">Filter</button></form>
<section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($properties as $property)<article class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-orange-600">{{ $property->business->name }}</p><h2 class="mt-1 font-extrabold">{{ $property->name }}</h2><p class="mt-1 text-xs text-slate-500">{{ $property->code }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{{ str($property->publication_status->value)->title() }}</span></div><p class="mt-4 text-sm text-slate-600">{{ str($property->property_type)->replace('_',' ')->title() }} · {{ $property->capacity }} guests · {{ $property->pricing_currency }} {{ number_format((float)$property->default_nightly_price) }}</p><a href="{{ route('admin.properties.show',$property) }}" class="mt-4 inline-flex rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white">Review property</a></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center md:col-span-2 xl:col-span-3">No properties match these filters.</div>@endforelse</section>{{ $properties->links() }}
</main></body></html>
